### ISSUE TITLE
sujana-kamasany

### ISSUE THREAD

**Issue by sujana-kamasany** [EddieHubCommunity/awesome-github-profiles#1030]
## Profile Screenshot

![image](https://user-images.githubusercontent.com/67040886/153723313-f1377db6-9b25-4496-a3cc-5e3c71583d75.png)

[Image Link](https://user-images.githubusercontent.com/67040886/153723313-f1377db6-9b25-4496-a3cc-5e3c71583d75.png)

**Comment by Pradumnasaraf** [comment]
Thank you for opening the Issue. I think it's no more required.
