### ISSUE TITLE
Atul Kumar Awasthi

### ISSUE THREAD

**Issue by kumaratul60** [EddieHubCommunity/awesome-github-profiles#1036]
## Profile Screenshot

![my-github profile](https://user-images.githubusercontent.com/53579888/153742966-50ce0f3f-468c-4472-ad38-b82493b27606.png)

**Comment by Pradumnasaraf** [comment]
Thank you for opening the Issue. I think it's no more required.

**Comment by kumaratul60** [comment]
I'm not able to see my profile on [awesome-github-profiles](https://eddiehubcommunity.github.io/awesome-github-profiles/)

**Comment by Pradumnasaraf** [comment]
> I'm not able to see my profile on [awesome-github-profiles](https://eddiehubcommunity.github.io/awesome-github-profiles/)

Your PR is not merged, feel free to open a new one.
