### ISSUE TITLE
rosalinet

### ISSUE THREAD

**Issue by rosalinet** [EddieHubCommunity/awesome-github-profiles#1039]
![MyGithubProfile](https://user-images.githubusercontent.com/92281462/153999153-c91b3f52-9a55-4c6f-a334-cd272484d8f2.png)

**Comment by debaghosh** [comment]
Your profile looks so good! 😍

**Comment by Pradumnasaraf** [comment]
Thank you for opening the Issue. I think it's no more required. Feel free to raise another one if required.
