### ISSUE TITLE
Add link to `README.md` that links to the `profiles.md` file

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/awesome-github-profiles#1052]
In order for everyone to see the awesome github profiles, a link to the `profiles.md` would be helpful. This is because I was confused as I was trying to find all the actual screenshots of everone's profiles, but I couldn't see them. I was going to put an issue up to ask where they all were, but then searched through the file directories, and found the `profiles.md` file with all the screenshots.
If this is possible, this is a beginner contributor issue, that anyone can contribute to.
Thank you.

**Comment by arpanaditya** [comment]
Hey, you can find these screenshots on the website also. Why don't you take the chance and contribute it by yourself?

**Comment by CodingSpecies** [comment]
@arpanaditya which website do you mean? If you mean: https://eddiehubcommunity.github.io/awesome-github-profiles/ , they don't seem to be there. Thank you.

**Comment by hasnainmakada-99** [comment]
Hey @CodingSpecies I would like to work on this issue can you please assign it to me

**Comment by CodingSpecies** [comment]
@hasnainmakada-99 feel free to work on it, but a maintainer will have to assign you. Thanks.

**Comment by hasnainmakada-99** [comment]
Okk and who's the maintainer

**Comment by CodingSpecies** [comment]
@hasnainmakada-99 you can work on the project without being assigned - if anyone else has decided to work on this, we will tell them that you are the assignee for this issue.
Maintainers such as @Panquesito7 will assign you to this. Any other questions feel free to ask, Thank you

**Comment by hasnainmakada-99** [comment]
Ok @CodingSpecies I'll start working on it
