### ISSUE TITLE
Bhumika Tewary

### ISSUE THREAD

**Issue by bhumikatewary** [EddieHubCommunity/awesome-github-profiles#1053]
## Profile Screenshot

![bhumikatewary](https://user-images.githubusercontent.com/77784592/155981066-6b9997be-35b8-4c26-b8e7-e7fbb51bbf8f.png)

**Comment by schmelto** [comment]
Hey,

you can add your profile by adding a PR described in the Readme.
I think you have forgot to create a Pull Request to this Repo.

Feel free to reopen the issue.
