### ISSUE TITLE
Mayank Goel

### ISSUE THREAD

**Issue by yellowberard** [EddieHubCommunity/awesome-github-profiles#1072]
## Profile Screenshot

![image](https://user-images.githubusercontent.com/82977727/157932738-208fbcc8-f06b-499c-898d-d77871580d67.png)
![image](https://user-images.githubusercontent.com/82977727/157932774-67f7d94b-74d5-4141-abf0-073912e1622c.png)
![image](https://user-images.githubusercontent.com/82977727/157932791-15646443-07e2-45ed-b616-0c246486820e.png)

**Comment by schmelto** [comment]
Hey,

you can add your profile by adding a PR described in the Readme.

Feel free to reopen the issue.
