### ISSUE TITLE
wrong name assigned to one of the profiles

### ISSUE THREAD

**Issue by Abiola-Farounbi** [EddieHubCommunity/awesome-github-profiles#108]
The wrong name was assigned to the 6th profile.

**Comment by Abiola-Farounbi** [comment]
I would like to be assigned this issue

**Comment by eddiejaoude** [comment]
Good spot, thanks @Abiola-Farounbi 👍

**Comment by schmelto** [comment]
Due this issue is fixed I will close this one :) Great spot btw 🚀
