### ISSUE TITLE
Abiola Farounbi

### ISSUE THREAD

**Issue by Abiola-Farounbi** [EddieHubCommunity/awesome-github-profiles#110]
![Screenshot_2020-10-01 Abiola-Farounbi - Overview(1)](https://user-images.githubusercontent.com/49586787/94759122-fd06ef80-0396-11eb-9014-e0ac0226ea49.png)

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one.

**Comment by Abiola-Farounbi** [comment]
Thanks
