### ISSUE TITLE
Default tweet text fix

### ISSUE THREAD

**Issue by zairahira** [EddieHubCommunity/awesome-github-profiles#1109]
I fixed some issues in the default tweet message for sharing the certificate:

I just completed the @eddiejaoude course on customizing my GitHub Profile so I can stand out! I learned: markdown, dynamic data using widgets, and  GitHub Actions - try it too! Also, join the inclusive Open Source community EddieHub on GitHub Org and Discord  http://eddiehub.org 

After the fix, however, the tweet text limit is breached.

**The original tweet:**
I just completed the @eddiejaoude course on customising my GitHub Profile so I can standout! I learnt: markdown, dynamic data using widgets and  GitHub Actions - try it too! Also join the inclusive Open Source community EddieHub on GitHub Org and Discord  http://eddiehub.org

**Comment by jaas666** [comment]
Hmm that's strange. It is under the 280 characters limit.

BTW, that URL throws an error.. this one shows the correct site. `https://www.eddiehub.org`
