### ISSUE TITLE
Remove profiles that don't exist anymore

### ISSUE THREAD

**Issue by ioanat94** [EddieHubCommunity/awesome-github-profiles#1126]
While browsing through the profiles I noticed that quite a few of them don't seem to exist anymore.

I was thinking they should maybe be removed?

If so, I wouldn't mind handling it. I assume it's just a matter of deleting the corresponding json files.

![awesome-github-profiles](https://user-images.githubusercontent.com/40671491/168739812-8be41a9a-50dd-4879-b0be-5ca5797fc3f6.gif)

**Comment by hasnainmakada-99** [comment]
Hey @ioanat94 i would like to work on this issue can you please assign it to me

**Comment by devaaquib** [comment]
@ioanat94 i updated my profile but it still not showing 😣

**Comment by Pradumnasaraf** [comment]
Thank you for opening the Issue. I think it's no more required. Feel free to raise another one if required.
