### ISSUE TITLE
Sulagna Dutta Roy

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [EddieHubCommunity/awesome-github-profiles#1127]
## Profile Screenshot

![github com_Sulagna-Dutta-Roy](https://user-images.githubusercontent.com/72568715/168895359-9450e341-9208-4fea-a053-84d1deefa456.png)

**Comment by abh139** [comment]
LGTM

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly review my PR. It's been 6days
