### ISSUE TITLE
Patricia Diaz

### ISSUE THREAD

**Issue by patriciadevelops** [EddieHubCommunity/awesome-github-profiles#1168]
<img width="1182" alt="Screen Shot 2022-06-13 at 3 59 15 AM" src="https://user-images.githubusercontent.com/15069545/173307507-7917cca8-4dba-465b-bb3c-321d82cb5997.png">

**Comment by Pradumnasaraf** [comment]
Thank you for opening the Issue. I think it's no more required. Feel free to raise another one if required.
