### ISSUE TITLE
Akas Rai

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/awesome-github-profiles#12]
<img width="1347" alt="Screenshot 2020-07-22 02 26 57" src="https://user-images.githubusercontent.com/624760/88123456-d40df580-cbc2-11ea-9add-a7fc8675b243.png">

**Comment by swaubhik** [comment]
nice

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one.

**Comment by MaseeraAhmed** [comment]
cooll!
