### ISSUE TITLE
Saiful Emon

### ISSUE THREAD

**Issue by saifulemon** [EddieHubCommunity/awesome-github-profiles#1206]
## Profile Screenshot

![screencapture-github-saifulemon-2022-06-26-08_10_22](https://user-images.githubusercontent.com/83161488/175789290-aae94e39-6e23-461e-b8d3-24d9e26b3114.png)

**Comment by meherulahmmed** [comment]
wow

**Comment by Pradumnasaraf** [comment]
Thank you for opening the Issue. I think it's no more required. Feel free to raise another one if required.
