### ISSUE TITLE
Ritika Das

### ISSUE THREAD

**Issue by Ritika-Das** [EddieHubCommunity/awesome-github-profiles#121]
![image](https://user-images.githubusercontent.com/61988162/94970758-f907d880-0522-11eb-91fc-2c0c0b48b735.png)

**Comment by NirmalSilwal** [comment]
Love this one.

**Comment by Ritika-Das** [comment]
> Love this one.

Thanks @NirmalSilwal !

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one.
