### ISSUE TITLE
Amandeep Singh

### ISSUE THREAD

**Issue by Amandeep404** [EddieHubCommunity/awesome-github-profiles#1227]
![Screenshot 2022-07-13 173946](https://user-images.githubusercontent.com/107784525/178730486-d5db66d4-024c-41db-b1a5-f2508e6b4db4.png)
![Screenshot 2022-07-13 174054](https://user-images.githubusercontent.com/107784525/178730497-a460aa1e-f7b9-4e60-b656-77cf8bd5de10.png)

**Comment by Pradumnasaraf** [comment]
Thank you for opening the Issue. I think it's no more required. Feel free to raise another one if required.
