### ISSUE TITLE
Shyam Praveen Singh

### ISSUE THREAD

**Issue by ShyamPraveenSingh** [EddieHubCommunity/awesome-github-profiles#123]
![Shyam](https://user-images.githubusercontent.com/57350162/94983126-66385f80-055d-11eb-9193-1cd683dd677b.png)

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one.

**Comment by ShyamPraveenSingh** [comment]
sure @schmelto
