### ISSUE TITLE
zayidmohamedy

### ISSUE THREAD

**Issue by zayidmohamedy** [EddieHubCommunity/awesome-github-profiles#1236]
## Profile Screenshot

![image](https://user-images.githubusercontent.com/65617964/179155665-a3a09961-5d1e-43d5-91eb-7772c0e0d8ff.png)
 
![image](https://user-images.githubusercontent.com/65617964/179156198-1580621f-4eaa-4368-8480-92ffe6859dda.png)

**Comment by schmelto** [comment]
Feel free to open a pr for your profile to be added.
