### ISSUE TITLE
Michelle Sandford

### ISSUE THREAD

**Issue by codess-aus** [EddieHubCommunity/awesome-github-profiles#125]
![image](https://user-images.githubusercontent.com/5952956/94992077-f86e5100-05b9-11eb-819a-73fe944f59c3.png)
![image](https://user-images.githubusercontent.com/5952956/94992099-29e71c80-05ba-11eb-817f-e98fbfd05b16.png)
![image](https://user-images.githubusercontent.com/5952956/94992113-4a16db80-05ba-11eb-99f8-91427c21c15a.png)

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one.
