### ISSUE TITLE
Typo mistake in readme.md file

### ISSUE THREAD

**Issue by jasham** [EddieHubCommunity/awesome-github-profiles#1336]
In the second line of the readme.MD file

***Feel free to submit a [pull request](https://github.com/EddieHubCommunity/awesome-github-profiles/pulls) with your suggestions of awesome GitHub profiles.***

In the place of ***of awesome*** it should be ***for awesome***

**Comment by Panquesito7** [comment]
Hey! This is a great catch. Would you like to work on this or let someone else do it?

**Comment by jasham** [comment]
Sure. @Panquesito7

**Comment by jasham** [comment]
Please assign it to me.
