### ISSUE TITLE
Typo mistake --- 2  ---> readme.md file

### ISSUE THREAD

**Issue by jasham** [EddieHubCommunity/awesome-github-profiles#1337]
In the readme.MD file

***Create an [issue](https://github.com/EddieHubCommunity/awesome-github-profiles/issues), with the title as your name, and in the description put a screenshot of the customised GitHub***

In the place of ***customised GitHub*** it should be ***customized GitHub***

**Comment by Panquesito7** [comment]
Hey! `Customized` is used in USA English, but
`Customised` is used outside USA English (in this case, UK).

I'll close this issue for now. Thanks. 🙂

**Comment by jasham** [comment]
But if you see in the same file in one place it is written as customization and in another place it is written as customised. Attaching the snapshot.
![image](https://user-images.githubusercontent.com/23471755/187008043-76e368d9-9780-41af-8c69-853b8de0e779.png)
