### ISSUE TITLE
Setup Commitlint to enhance the developer experience 

### ISSUE THREAD

**Issue by KashishLakhara04** [EddieHubCommunity/awesome-github-profiles#1395]
- Setup Commitlint and Configure commitlint to use conventional config ``@commitlint/config-conventional``

### **How Commitlint helps?**
-  Commitlint helps your team adhere to a commit convention. It makes sharing of commit conventions easy.
### **Resources**

- Guide to [Commitlint setup](https://commitlint.js.org/#/guides-local-setup)
- Learn more about [Conventional Commit Message](https://www.conventionalcommits.org/en/v1.0.0/)

I would like to work on this issue.

**Comment by jyotika6221** [comment]
Hey is the issue still open? I would like to work on it under hacktoberfest.

**Comment by Pradumnasaraf** [comment]
Hey,

Sometime commitlint can be a blocker for new contributors also most people add their profiles through UI. Thank you for opening the issue.
