### ISSUE TITLE
Dipto Chakrabarty

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/awesome-github-profiles#14]
<img width="1347" alt="Screenshot 2020-07-22 10 56 31" src="https://user-images.githubusercontent.com/624760/88163171-2d4d4780-cc0a-11ea-91fe-6fc7c37fc8d6.png">

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one.
