### ISSUE TITLE
Shivam Jha

### ISSUE THREAD

**Issue by shivam-jha2712** [EddieHubCommunity/awesome-github-profiles#1412]
## Profile Screenshot

![Screenshot (1298)](https://user-images.githubusercontent.com/71783722/193400352-b6016c78-03cb-4015-8e44-d45a97284a76.png)

**Comment by shivam-jha2712** [comment]
I guess this is not participating in Hacktober right

**Comment by Pradumnasaraf** [comment]
> I guess this is not participating in Hacktober right

Yes, it will not be counted
