### ISSUE TITLE
Sanskar

### ISSUE THREAD

**Issue by SanskarJain007** [EddieHubCommunity/awesome-github-profiles#1475]
![Screenshot (11)](https://user-images.githubusercontent.com/78869626/194513709-69a280aa-63c8-4d9a-9527-2191664545d0.png)

![Screenshot (12)](https://user-images.githubusercontent.com/78869626/194513719-de040652-0a21-480c-8560-4f95c18e3176.png)

**Comment by halimkun** [comment]
I think you try to provide a screen capture using a **light theme**.

because some of the components in the github profile that you provide may be more suitable for viewing from a light theme, and will look more attractive. sara guess it will make it _more interesting_.
