### ISSUE TITLE
Added profiles not displayed in website

### ISSUE THREAD

**Issue by pythonhubdev** [EddieHubCommunity/awesome-github-profiles#1487]
Hi, new profiles that are being merged in the repo are not being displayed on the website. I guess a new deployment needs to be done. If there is any other issue we can work on it and raise a PR. Thank you.

**Comment by Panquesito7** [comment]
Seems it has to be deployed manually? Not sure how we do that, though.

https://github.com/EddieHubCommunity/awesome-github-profiles/actions/workflows/pages/pages-build-deployment
CC: @eddiejaoude, @naomi-lgbt.

**Comment by pythonhubdev** [comment]
Yeah, deployment has been done 8 months back that's the reason I guess.

**Comment by eddiejaoude** [comment]
Thank you for raising the issue 👍 , yes it was a bug, I think I have fixed it now 🤓
