### ISSUE TITLE
Shantanu Raut

### ISSUE THREAD

**Issue by s4shantanu** [EddieHubCommunity/awesome-github-profiles#1516]
## Profile Screenshot

![Screenshot 2022-10-27 at 11 54 06 PM](https://user-images.githubusercontent.com/67189790/198369127-b146b5cd-8db4-4203-9d82-d0fb38b91a10.png)

**Comment by schmelto** [comment]
Feel free to open a pr for your profile to be added.

**Comment by s4shantanu** [comment]
Thank you @Pradumnasaraf
