### ISSUE TITLE
[DOCS] Update `package.json` description

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/awesome-github-profiles#1522]
# Description

The current package description in the `package.json` file isn't proper, IMO. We should update it.

## Steps to contribute

_If you've already forked the repository, skip to step 3_

1. Fork the repository [**here**](https://github.com/EddieHubCommunity/awesome-github-profiles/fork).
2. Make a branch named `update_description`.
3. Open the `package.json` file.
4. In line 4, update the text to

```json
  "description": "List of GitHub profiles that have awesome customisation, that you can use for inspiration.",
```

5. Commit and push your changes.
6. You're done! 🎉 You need to make a [**pull request**](https://github.com/EddieHubCommunity/awesome-github-profiles/compare), and the maintainers will review it as soon as they can.

If you need any help, let us know! 🙂
Don't forget to leave this to first-timers and beginners.

**Comment by gogoiakash2311** [comment]
Heyy @Panquesito7 I'm about to make a PR regarding this issue. While making the PR, do I need to follow the default template?
