### ISSUE TITLE
[BUG] Outdated badge link

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/awesome-github-profiles#1535]
### Description

The badge on the `README.md` file is currently using an outdated link (`EddieJaoudeCommunity`, which should be `EddieHubCommunity` now). It's not critical as GitHub will redirect you, but to maintain things clean, it should be updated.

### Steps to contribute

_If you've already forked the repository, skip to step 3_

1. Fork the repository [**here**](https://github.com/EddieHubCommunity/awesome-github-profiles/fork).
2. Make a new branch named `fix_link`.
3. Open the `README.md` file.
4. On the 3rd line of `README.md`, replace the current content with the following content:

```markdown
[![Read/Write profiles' data](https://github.com/EddieHubCommunity/awesome-github-profiles/actions/workflows/main.yml/badge.svg)](https://github.com/EddieHubCommunity/awesome-github-profiles/actions/workflows/main.yml)
```

5. Commit and push your changes.
6. You're done! 🎉 You just have to create a [**pull request**](https://github.com/EddieHubCommunity/awesome-github-profiles/compare) and the maintainers will review it.

### Additional information

If you need any help, let us know! 🙂

**Comment by gogoiakash2311** [comment]
I have made a PR please check #1535
