### ISSUE TITLE
GitHub action creates undefined links

### ISSUE THREAD

**Issue by frankiefab100** [EddieHubCommunity/awesome-github-profiles#154]
<a href="https://github.com/undefined">Ankush Singh Gandhi</a></p><img src="https://user-images.githubusercontent.com/24972335/96338880-96bde480-1099-11eb-8b76-f6a39292477a.png" /><p><a href="https://github.com/EddieJaoudeCommunity/awesome-github-profiles/issues/undefined">

**Comment by eddiejaoude** [comment]
Oh thats news, why are links suddenly all undefined 😱

**Comment by eddiejaoude** [comment]
`Michelle Sandford`'s link is fine, then from there they are undefined 🤔

**Comment by keshavsingh4522** [comment]
@frankiefab100  correct link >> https://github.com/AnkushSinghGandhi

**Comment by schmelto** [comment]
Link to https://github.com/AnkushSinghGandhi is working for me. I close this issue now.
If there is anything more please feel free to reopen the issue.
