### ISSUE TITLE
Harsh Kumar Khatri

### ISSUE THREAD

**Issue by harshkumarkhatri** [EddieHubCommunity/awesome-github-profiles#158]
![Screenshot from 2020-10-29 21-20-53](https://user-images.githubusercontent.com/42743629/97598257-c28f8180-1a2c-11eb-859a-5902efa7a828.png)

**Comment by harshkumarkhatri** [comment]
Check PR:- https://github.com/EddieJaoudeCommunity/awesome-github-profiles/pull/159

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one. Nice Profile btw 🚀
