### ISSUE TITLE
Akshita Gupta

### ISSUE THREAD

**Issue by akshitagupta15june** [EddieHubCommunity/awesome-github-profiles#160]
![image](https://user-images.githubusercontent.com/57909583/97854357-58722780-1d1f-11eb-8bda-83425c231ff5.png)

**Comment by akshitagupta15june** [comment]
@eddiejaoude please have a look

**Comment by eddiejaoude** [comment]
Please read the documentation in the `README.md` https://github.com/EddieJaoudeCommunity/awesome-github-profiles#to-add-your-github-profile

**Comment by akshitagupta15june** [comment]
@eddiejaoude i am very sorry, i will follow the rules and give issue.
Thankyou for guiding.

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one. Nice Profile btw 🚀

**Comment by akshitagupta15june** [comment]
Thanks!
