### ISSUE TITLE
The link to profiles is not properly given

### ISSUE THREAD

**Issue by ErrolFernandes** [EddieHubCommunity/awesome-github-profiles#1610]
In the readme file and the website 
in the line "checkout awesome github profile here" 
when i click "here" it opens the same page instead of the profiles pages

**Comment by Panquesito7** [comment]
Hmm, you're right. We might want to change the link to https://eddiehubcommunity.github.io/awesome-github-profiles/profiles.
Let's see what the others think about this. Thanks. 🙂

**Comment by BoseSj** [comment]
On the one hand, this seems like an easy fix but on the other, the given link takes us to this _awesome-github-profiles_ [page](https://eddiehubcommunity.github.io/awesome-github-profiles/) . Now there is a couple of problems to deal with
- The same wrong link given in the README file is also given on this [page](https://eddiehubcommunity.github.io/awesome-github-profiles/) . As result tapping on it is causing a never-ending loop.
- We could just fix the link in README, but then what about the _awesome-github-profiles_ page then?
