### ISSUE TITLE
[OTHER] Add a favicon to the website

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/awesome-github-profiles#1625]
### Description

We can add a favicon to the website to make it look more stylish.
What icon should we use? I was thinking of EddieHub's mascot. 🤔

**Comment by Im-vishalanand** [comment]
Also, In the view profile section, we can add the padding and border along with border radius to make it more attractive.

**Comment by Rishav1707** [comment]
How to run this repo in our local system? @Panquesito7

**Comment by Panquesito7** [comment]
> How to run this repo in our local system? @Panquesito7

It's [an HTML page](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/_layouts/default.html). It should work by opening the page, I guess.

> we can add the padding and border along with border radius

Feel free to create a PR for that and show how it looks! Thank you. :)
