### ISSUE TITLE
Yajush Vyas

### ISSUE THREAD

**Issue by notsoocool** [EddieHubCommunity/awesome-github-profiles#163]
<img width="1440" alt="Screenshot 2020-11-08 at 8 04 50 PM" src="https://user-images.githubusercontent.com/35025375/98467874-c924b280-21fd-11eb-810b-2d17e0342e10.png">

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one. Nice Profile btw 🚀
