### ISSUE TITLE
[BUG] Trailing comma in profile

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/awesome-github-profiles#1642]
### Description

There's a trailing/extra comma in [Siddhesh Agarwal](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/profiles/Siddhesh-Agarwal.json)'s recently added profile.
This should be fixed immediately to prevent CI and deployment issues.

_Steps to contribute_

1. Fork the repository [here](https://github.com/EddieHubCommunity/awesome-github-profiles/fork).
2. Create a new branch named `fix_comma`.
3. Open the [`profiles/Siddesh-Agarwal.json`](https://github.com/EddieHubCommunity/awesome-github-profiles/blob/main/profiles/Siddhesh-Agarwal.json) file.
4. In line 5, in the `username` field, remove the comma at the end of it.
5. Commit and push your changes.
6. Create a [pull request](https://github.com/EddieHubCommunity/awesome-github-profiles/compare) in the repository.
7. You're done now! 🎉 You just have to wait until the maintainers check your PR.

If you need any help, let us know about it and we'll gladly help.

### Additional information

This is a good first issue. Please leave it open to first-time contributors and beginners. 🙂

**Comment by imbhaskarn** [comment]
@Panquesito7 I will fix it.

**Comment by imbhaskarn** [comment]
https://github.com/EddieHubCommunity/awesome-github-profiles/pull/1644
