### ISSUE TITLE
Mohit Rakhade

### ISSUE THREAD

**Issue by mohitrakhade20** [EddieHubCommunity/awesome-github-profiles#168]

**Comment by mohitrakhade20** [comment]
![image](https://user-images.githubusercontent.com/48031017/98556319-eecabe00-22c8-11eb-8692-57d2efa3d3ab.png)

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one. Nice Profile btw 🚀
