### ISSUE TITLE
Jayant Goel

### ISSUE THREAD

**Issue by JayantGoel001** [EddieHubCommunity/awesome-github-profiles#169]
![potfoliopic](https://user-images.githubusercontent.com/54479676/98487992-88a05580-224c-11eb-8e76-d8a59aa05bd4.png)

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one. Nice Profile btw 🚀

**Comment by DonGuillotine** [comment]
This is the best profile I've seen on GitHub 🔥, Great Job!  I am inspired.

**Comment by JayantGoel001** [comment]
Thanks a lot @DonGuillotine 😁🎉

**Comment by DonGuillotine** [comment]
> Thanks a lot @DonGuillotine 😁🎉

Any tips for me, would love to have a profile like yours.

**Comment by JayantGoel001** [comment]
Hi @DonGuillotine,
Sorry for the late reply,
Well, Github Profile is based on your imagination power i.e. simply how you want to show your profile or represent yourself to others.
The best way according to me is by looking at other people's profiles & try to make something that **you** like:

1. https://github.com/EddieHubCommunity/awesome-github-profiles
2. https://github.com/abhisheknaiidu/awesome-github-profile-readme
3. https://www.youtube.com/watch?v=9c5xweuO2DA
4. https://www.youtube.com/watch?v=ECuqb5Tv9qI
5. https://bootcamp.uxdesign.cc/how-to-design-an-attractive-github-profile-readme-3618d6c53783
6. https://towardsdatascience.com/create-a-simple-continuous-integration-ci-for-medium-rss-feed-in-github-profile-readme-b5dc6fdf6315

Happy Coding🎉 ,
Let me know if there is anything I can do to help you.😊

**Comment by DonGuillotine** [comment]
> Hi @DonGuillotine, Sorry for the late reply, Well, Github Profile is based on your imagination power i.e. simply how you want to show your profile or represent yourself to others. The best way according to me is by looking at other people's profiles & try to make something that **you** like:
> 
> 1. https://github.com/EddieHubCommunity/awesome-github-profiles
> 2. https://github.com/abhisheknaiidu/awesome-github-profile-readme
> 3. https://www.youtube.com/watch?v=9c5xweuO2DA
> 4. https://www.youtube.com/watch?v=ECuqb5Tv9qI
> 5. https://bootcamp.uxdesign.cc/how-to-design-an-attractive-github-profile-readme-3618d6c53783
> 6. https://towardsdatascience.com/create-a-simple-continuous-integration-ci-for-medium-rss-feed-in-github-profile-readme-b5dc6fdf6315
> 
> Happy Coding🎉 , Let me know if there is anything I can do to help you.😊

Thanks a lot, I have created mine. How do you get so many green dots? Are all of them from your personal projects or open source contributions?

**Comment by JayantGoel001** [comment]
> > Hi @DonGuillotine, Sorry for the late reply, Well, Github Profile is based on your imagination power i.e. simply how you want to show your profile or represent yourself to others. The best way according to me is by looking at other people's profiles & try to make something that **you** like:
> > 
> > 1. https://github.com/EddieHubCommunity/awesome-github-profiles
> > 2. https://github.com/abhisheknaiidu/awesome-github-profile-readme
> > 3. https://www.youtube.com/watch?v=9c5xweuO2DA
> > 4. https://www.youtube.com/watch?v=ECuqb5Tv9qI
> > 5. https://bootcamp.uxdesign.cc/how-to-design-an-attractive-github-profile-readme-3618d6c53783
> > 6. https://towardsdatascience.com/create-a-simple-continuous-integration-ci-for-medium-rss-feed-in-github-profile-readme-b5dc6fdf6315
> > 
> > Happy Coding🎉 , Let me know if there is anything I can do to help you.😊
> 
> Thanks a lot, I have created mine. How do you get so many green dots? Are all of them from your personal projects or open source contributions?

Most of Them are my personal Projects.
I guess around 50 to 60 repositories are open sources.

**Comment by DonGuillotine** [comment]
> > > Hi @DonGuillotine, Sorry for the late reply, Well, Github Profile is based on your imagination power i.e. simply how you want to show your profile or represent yourself to others. The best way according to me is by looking at other people's profiles & try to make something that **you** like:
> > > 
> > > 1. https://github.com/EddieHubCommunity/awesome-github-profiles
> > > 2. https://github.com/abhisheknaiidu/awesome-github-profile-readme
> > > 3. https://www.youtube.com/watch?v=9c5xweuO2DA
> > > 4. https://www.youtube.com/watch?v=ECuqb5Tv9qI
> > > 5. https://bootcamp.uxdesign.cc/how-to-design-an-attractive-github-profile-readme-3618d6c53783
> > > 6. https://towardsdatascience.com/create-a-simple-continuous-integration-ci-for-medium-rss-feed-in-github-profile-readme-b5dc6fdf6315
> > > 
> > > Happy Coding🎉 , Let me know if there is anything I can do to help you.😊
> > 
> > 
> > Thanks a lot, I have created mine. How do you get so many green dots? Are all of them from your personal projects or open source contributions?
> 
> Most of Them are my personal Projects. I guess around 50 to 60 repositories are open sources.

Wow! How do I find open source projects to contribute to?

**Comment by JayantGoel001** [comment]
> > > > Hi @DonGuillotine, Sorry for the late reply, Well, Github Profile is based on your imagination power i.e. simply how you want to show your profile or represent yourself to others. The best way according to me is by looking at other people's profiles & try to make something that **you** like:
> > > > 
> > > > 1. https://github.com/EddieHubCommunity/awesome-github-profiles
> > > > 2. https://github.com/abhisheknaiidu/awesome-github-profile-readme
> > > > 3. https://www.youtube.com/watch?v=9c5xweuO2DA
> > > > 4. https://www.youtube.com/watch?v=ECuqb5Tv9qI
> > > > 5. https://bootcamp.uxdesign.cc/how-to-design-an-attractive-github-profile-readme-3618d6c53783
> > > > 6. https://towardsdatascience.com/create-a-simple-continuous-integration-ci-for-medium-rss-feed-in-github-profile-readme-b5dc6fdf6315
> > > > 
> > > > Happy Coding🎉 , Let me know if there is anything I can do to help you.😊
> > > 
> > > 
> > > Thanks a lot, I have created mine. How do you get so many green dots? Are all of them from your personal projects or open source contributions?
> > 
> > 
> > Most of Them are my personal Projects. I guess around 50 to 60 repositories are open sources.
> 
> Wow! How do I find open source projects to contribute to?

Hi @DonGuillotine 
Well, the easiest way to start working on an open-source project is to first know the basic of any language or framework and then search from issues rather than from projects directly. There are maintainers looking for contributors who usually add labels to some issues to manifest their interest in having public contributions. You can simply search for the tech that you are comfortable with using GitHub search & try to look for the project that active maintainers and contributors. That will make development more smooth and more interesting. 

Thanks & Regards,
Happy Coding 😊🎉

**Comment by DonGuillotine** [comment]
> > > > > Hi @DonGuillotine, Sorry for the late reply, Well, Github Profile is based on your imagination power i.e. simply how you want to show your profile or represent yourself to others. The best way according to me is by looking at other people's profiles & try to make something that **you** like:
> > > > > 
> > > > > 1. https://github.com/EddieHubCommunity/awesome-github-profiles
> > > > > 2. https://github.com/abhisheknaiidu/awesome-github-profile-readme
> > > > > 3. https://www.youtube.com/watch?v=9c5xweuO2DA
> > > > > 4. https://www.youtube.com/watch?v=ECuqb5Tv9qI
> > > > > 5. https://bootcamp.uxdesign.cc/how-to-design-an-attractive-github-profile-readme-3618d6c53783
> > > > > 6. https://towardsdatascience.com/create-a-simple-continuous-integration-ci-for-medium-rss-feed-in-github-profile-readme-b5dc6fdf6315
> > > > > 
> > > > > Happy Coding🎉 , Let me know if there is anything I can do to help you.😊
> > > > 
> > > > 
> > > > Thanks a lot, I have created mine. How do you get so many green dots? Are all of them from your personal projects or open source contributions?
> > > 
> > > 
> > > Most of Them are my personal Projects. I guess around 50 to 60 repositories are open sources.
> > 
> > 
> > Wow! How do I find open source projects to contribute to?
> 
> Hi @DonGuillotine Well, the easiest way to start working on an open-source project is to first know the basic of any language or framework and then search from issues rather than from projects directly. There are maintainers looking for contributors who usually add labels to some issues to manifest their interest in having public contributions. You can simply search for the tech that you are comfortable with using GitHub search & try to look for the project that active maintainers and contributors. That will make development more smooth and more interesting.
> 
> Thanks & Regards, Happy Coding 😊🎉

Will Definitely try it out! Thanks
