### ISSUE TITLE
[PROFILE ADDITION] <Nicolette Renner>

### ISSUE THREAD

**Issue by nrenner0211** [EddieHubCommunity/awesome-github-profiles#1716]
### Profile screenshot

![ghprof](https://user-images.githubusercontent.com/92491816/217900335-73d55c89-4b22-4a0c-a442-03ac89d1b8fb.png)

**Comment by schmelto** [comment]
Closure Notice: This profile is being closed either because it has already been added or because no PR has been created. Please feel free to reopen and initiate a PR if the profile has not been added yet.
