### ISSUE TITLE
[OTHER]  Profile link is not working

### ISSUE THREAD

**Issue by Hat52** [EddieHubCommunity/awesome-github-profiles#1724]
### What would you like to share?

Page: https://eddiehubcommunity.github.io/awesome-github-profiles/
Section : How can I add my GitHub profile?

In the third point the given profile link doesn't take the user to the right page instead it display 404 error
![image](https://user-images.githubusercontent.com/44437268/218282628-8a9e7ac4-0c98-4d7a-b7ee-85df4b0d828e.png)

### Additional information

If the profile link is intended then it should display right information when clicked on it. Otherwise we can just set to to plan text.

**Comment by Hat52** [comment]
I would like to work on this issue.

**Comment by krshkun** [comment]
Go ahead @Hat52 open a PR for it 👍

**Comment by Hat52** [comment]
Should I go with fixing the link or should I go with removing the link all together.

**Comment by krshkun** [comment]
Fixing the link sounds better

**Comment by Hat52** [comment]
Where should it take the user then? 
Is their any page that I should redirect to or should I redirect to the git repo?
