### ISSUE TITLE
[PROFILE ADDITION] Lucy Linder (derlin)

### ISSUE THREAD

**Issue by derlin** [EddieHubCommunity/awesome-github-profiles#1734]
### Profile screenshot

![derlin](https://user-images.githubusercontent.com/5463445/219426621-70427e36-f66e-478d-bb3b-1f42dcf43dc5.png)

**Comment by schmelto** [comment]
Closure Notice: This profile is being closed either because it has already been added or because no PR has been created. Please feel free to reopen and initiate a PR if the profile has not been added yet.
