### ISSUE TITLE
[PROFILE ADDITION] Sidharth P

### ISSUE THREAD

**Issue by Sid-WC121** [EddieHubCommunity/awesome-github-profiles#1739]
### Profile screenshot

![Screenshot 2023-02-17 172955](https://user-images.githubusercontent.com/112648016/219649504-a796fa28-28e4-4d39-8d27-db8e42524947.jpg)

**Comment by schmelto** [comment]
Closure Notice: This profile is being closed either because it has already been added or because no PR has been created. Please feel free to reopen and initiate a PR if the profile has not been added yet.
