### ISSUE TITLE
[PROFILE ADDITION] <Nancy>

### ISSUE THREAD

**Issue by nancyKasaudhan20** [EddieHubCommunity/awesome-github-profiles#1764]
### Profile screenshot

![Screenshot_2023_0322_154851](https://user-images.githubusercontent.com/97733705/226874050-a1844b30-6f24-499d-885d-e812b8907c59.jpg)

**Comment by schmelto** [comment]
Closure Notice: This profile is being closed either because it has already been added or because no PR has been created. Please feel free to reopen and initiate a PR if the profile has not been added yet.
