### ISSUE TITLE
The Prettier linter, main.yml GitHub Actions Flow and Pull Request UI

### ISSUE THREAD

**Issue by stemount** [EddieHubCommunity/awesome-github-profiles#177]
- There is a slight issue with #173 where the GitHub `prettier-lint-check.yml` action happens on `push and pull_request update` whereas `main.yml` runs on `push`.

I've separated this issue as I wanted more of the community to get involved in understanding GitHub Actions and I'd love some feedback on what you think.

As in CircleCI, Travis and similar, you will find most CI/CD pipelines to be somewhat procedural, with the exceptions of well crafted "parallelism" where all parallel jobs must have a valid exit code or the entire job fails. You can also specify otherwise, e.g. parallelise all the things but let the developer know which tests did fail. (Think more than one language/stack in a mono-repo.)

This does open a problem as even if it does find a Prettier fault, it will ❌ that action, however that has ran **after** it has gone ahead and ran `main.yml`.

This may just be me, but this UI suggests quite the opposite of what is happening here:

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/150512/98675763-9a6c2080-2352-11eb-8e79-218c491bed3a.png">

### Suggestion:
Suggestion is to:

- collaborate on how to order these actions, check if these `on: [push]` and `on: [push, request]` is correct
- work on how we ensure that Prettier failing is really clear in the GitHub UI.
  - Because the `main.yml` awesome gihub profiles generator will run in parallel of the prettier-lint-check, even if the JSON is not exactly "pretty", it will look like it's got the all clear from the GitHub action/
  - **This separated file may not be best.** as they run in parallel.

**Comment by schmelto** [comment]
See also #211

**Comment by krishguptadev** [comment]
Can I try working on this?

**Comment by nhcarrigan** [comment]
I think this is no longer an issue with https://github.com/EddieHubCommunity/awesome-github-profiles/pull/881 merged.

**Comment by krshdev** [comment]
Can someone close this in that case? 😓
