### ISSUE TITLE
[PROFILE ADDITION] <Md Moinuddin>

### ISSUE THREAD

**Issue by Blaize15** [EddieHubCommunity/awesome-github-profiles#1773]
### Profile screenshot

![Github profile](https://user-images.githubusercontent.com/59837486/227793573-e25e160a-185e-4561-a79c-77a2058268a1.png)

**Comment by at-the-vr** [comment]
Hey @Blaize15 , need any assistance for the Issue ? Should be diagnosed quickly 😄

**Comment by schmelto** [comment]
Closure Notice: This profile is being closed either because it has already been added or because no PR has been created. Please feel free to reopen and initiate a PR if the profile has not been added yet.
