### ISSUE TITLE
Json Format

### ISSUE THREAD

**Issue by charan-web** [EddieHubCommunity/awesome-github-profiles#178]
Remove the outer squares and add a Curly braces'. " {}" And paste the object between. It is the correct way of Json

**Comment by eddiejaoude** [comment]
Not sure what you mean? The square brackets are to show an array / collection of objects.

**Comment by AllanRegush** [comment]
I think @charan-web means that the typical `json` structure is:
```js
{
   "items": 1,
   "things": "yes"
}
```
But in this case, we are using `Arrays as JSON`:
```js
[
    {
        "items": 1,
        "things": "yes"
    }
]
```

Both are legal `JSON`

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/JSON

**Comment by schmelto** [comment]
I think we can close this one for now. If there is anything else please reopen it and let us know :)
