### ISSUE TITLE
[PROFILE ADDITION] <Maq77>

### ISSUE THREAD

**Issue by maq77** [EddieHubCommunity/awesome-github-profiles#1787]
### Profile screenshot

![Screenshot_2023-04-05-23-55-06-83](https://user-images.githubusercontent.com/40144153/230220921-28467b34-b44f-483a-b49d-b336cc1cae98.png)

**Comment by schmelto** [comment]
Closure Notice: This profile is being closed either because it has already been added or because no PR has been created. Please feel free to reopen and initiate a PR if the profile has not been added yet.
