### ISSUE TITLE
[OTHER] json profiles out of profiles directory

### ISSUE THREAD

**Issue by at-the-vr** [EddieHubCommunity/awesome-github-profiles#1789]
### What would you like to share?

There are three json files outside of the `profiles` directory and are not available in the `profiles.md` file as well (I believe that's a task for the generate.js to update the markdown).

![Screenshot 2023-04-07 191011](https://user-images.githubusercontent.com/88548999/230618717-675eaf89-a311-4e6d-b58e-d7b41ce4f9a4.png)

### Additional information

Just a drag and drop needed, easy fix

**Comment by Panquesito7** [comment]
Hey there. Awesome catch! Would you like to work on this? 🙂

**Comment by at-the-vr** [comment]
Naah, I believe someone else should have a go at this

**Comment by Shalini469717** [comment]
Should I just drag and drop files?

**Comment by at-the-vr** [comment]
Go ahead, should not take long

**Comment by Pravesh-Sudha** [comment]
if @Shalini469717 is not working on it, Can I work on it?

**Comment by Shalini469717** [comment]
Ah I missed out the convo. Thanks for doing it @Pravesh-Sudha
