### ISSUE TITLE
Vedant Khairnar

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/awesome-github-profiles#18]
<img width="1363" alt="Screenshot 2020-07-22 11 21 15" src="https://user-images.githubusercontent.com/624760/88165360-7b177f00-cc0d-11ea-804a-776639dcca29.png">

**Comment by NirmalSilwal** [comment]
love the design

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one.
