### ISSUE TITLE
[PROFILE ADDITION] <Miniyahil Kebede>

### ISSUE THREAD

**Issue by hmhard** [EddieHubCommunity/awesome-github-profiles#1803]
### Profile screenshot

![screencapture-github-hmhard-2023-04-15-16_28_08](https://user-images.githubusercontent.com/53700166/232226923-248a50ae-6b92-4028-accf-337f621babfc.png)

**Comment by schmelto** [comment]
Closure Notice: This profile is being closed either because it has already been added or because no PR has been created. Please feel free to reopen and initiate a PR if the profile has not been added yet.
