### ISSUE TITLE
[PROFILE ADDITION] <Niaz Morshed>

### ISSUE THREAD

**Issue by NiazMorshed2007** [EddieHubCommunity/awesome-github-profiles#1810]
### Profile screenshot

![image](https://user-images.githubusercontent.com/77217706/233391030-0acd392b-8288-451c-b751-ed16a1809c45.png)

**Comment by at-the-vr** [comment]
Hey Niaz, i see your Issue is raised about 2 weeks ago. Wanna check it again ?
