### ISSUE TITLE
[PROFILE ADDITION] Priyansh Prajapat

### ISSUE THREAD

**Issue by priyazsh** [EddieHubCommunity/awesome-github-profiles#1816]
### Profile screenshot

![IMG_20230505_195101](https://oyepriyansh.pages.dev/i/59658985.png)

**Comment by schmelto** [comment]
Closure Notice: This profile is being closed either because it has already been added or because no PR has been created. Please feel free to reopen and initiate a PR if the profile has not been added yet.
