### ISSUE TITLE
[PROFILE ADDITION] Bilal Ahmed

### ISSUE THREAD

**Issue by bilalahmed14** [EddieHubCommunity/awesome-github-profiles#1828]
### Profile screenshot

![image](https://user-images.githubusercontent.com/81938708/238679768-3a0510af-f6cf-446c-9c9a-dd67767b163e.png)

**Comment by schmelto** [comment]
Closing due this profile either has been added or there is no PR created. Feel free to reopen and create a PR if the profile was not added.
