### ISSUE TITLE
wellingtonmwadali

### ISSUE THREAD

**Issue by wellingtonmwadali** [EddieHubCommunity/awesome-github-profiles#1841]
### Profile screenshot

![github screen shot](https://github.com/EddieHubCommunity/awesome-github-profiles/assets/121486233/06e063c7-96f4-4881-ac6a-ec184bdf9d0f)

**Comment by schmelto** [comment]
Closure Notice: This profile is being closed either because it has already been added or because no PR has been created. Please feel free to reopen and initiate a PR if the profile has not been added yet.
