### ISSUE TITLE
[Muhammad Hassan] <mhassanbughio>

### ISSUE THREAD

**Issue by Mhassanbughio** [EddieHubCommunity/awesome-github-profiles#1854]
### Profile screenshot
![GitHub](https://github.com/EddieHubCommunity/awesome-github-profiles/assets/60064591/e6d6f37f-3c7d-464f-8db5-4b5d01a28547)

**Comment by schmelto** [comment]
Closure Notice: This profile is being closed either because it has already been added or because no PR has been created. Please feel free to reopen and initiate a PR if the profile has not been added yet.
