### ISSUE TITLE
[PROFILE ADDITION] <Tanveer Khan>

### ISSUE THREAD

**Issue by Tanv33** [EddieHubCommunity/awesome-github-profiles#1865]
### Profile screenshot

![tanveer-github-readme-image](https://github.com/EddieHubCommunity/awesome-github-profiles/assets/79161723/d21d81d6-83d2-41cc-85a4-1758095dcc00)

**Comment by schmelto** [comment]
Closure Notice: This profile is being closed either because it has already been added or because no PR has been created. Please feel free to reopen and initiate a PR if the profile has not been added yet.
