### ISSUE TITLE
[PROFILE ADDITION] <Sahilll15>

### ISSUE THREAD

**Issue by Sahilll15** [EddieHubCommunity/awesome-github-profiles#1890]
### Profile screenshot

<img width="642" alt="Screenshot 2023-08-07 at 9 43 15 PM" src="https://github.com/EddieHubCommunity/awesome-github-profiles/assets/109215419/be6157bd-e4e0-4d09-b044-9edc54c9b5c8">

**Comment by schmelto** [comment]
Closing due this profile either has been added or there is no PR created. Feel free to reopen and create a PR if the profile was not added.
