### ISSUE TITLE
[OTHER] Broken link of Images in ReadMe file

### ISSUE THREAD

**Issue by manzil-infinity180** [EddieHubCommunity/awesome-github-profiles#1901]
### What would you like to share?

<img width="1497" alt="Screenshot 2023-08-24 at 12 06 47 AM" src="https://github.com/EddieHubCommunity/awesome-github-profiles/assets/119070053/12c0591a-0efa-40cc-aad2-20c6ae5119e2">

**Comment by suryan-s** [comment]
Why aren't the badges working anymore?

**Comment by schmelto** [comment]
![image](https://github.com/EddieHubCommunity/awesome-github-profiles/assets/30869493/deeae4bc-d738-4d3c-9708-8ae5ee08be7b)

**Comment by manzil-infinity180** [comment]
> -> remove badges or use for example shields io
check it out sir , raised a pr
https://github.com/EddieHubCommunity/awesome-github-profiles/pull/1904
