### ISSUE TITLE
[PROFILE ADDITION] Sapana saraf

### ISSUE THREAD

**Issue by sapanasaraf** [EddieHubCommunity/awesome-github-profiles#1908]
### Profile screenshot

<img width="1512" alt="Screenshot 2023-09-11 at 10 12 49 AM" src="https://github.com/EddieHubCommunity/awesome-github-profiles/assets/144257966/81f093c7-8278-49fe-8f4b-a19ef4d93274">

**Comment by schmelto** [comment]
closing. there was no corresponding pull request. Feel free to reopen at anytime
