### ISSUE TITLE
[OTHER] link is giving 404 error 

### ISSUE THREAD

**Issue by KISHANsingh0001** [EddieHubCommunity/awesome-github-profiles#1909]
### This link is giving 404 error .

Check out our awesome profiles [here](https://eddiehubcommunity.github.io/awesome-github-profiles/profiles)
---

### Additional information
![Screenshot 2023-09-11 201524](https://github.com/EddieHubCommunity/awesome-github-profiles/assets/126978912/75e138ae-b66f-4713-87bf-55fa8ac78baa)

**Comment by Panquesito7** [comment]
Seems to be fixed now. The page wasn't being deployed.
