### ISSUE TITLE
[PROFILE ADDITION] <Utkarsh-Upadhyay>

### ISSUE THREAD

**Issue by utk2103** [EddieHubCommunity/awesome-github-profiles#1929]
### Profile screenshot

![image](https://github.com/EddieHubCommunity/awesome-github-profiles/assets/118432516/3c34b7be-3ec8-459a-a6be-67e8195b30a0)

**Comment by schmelto** [comment]
closing. there was no corresponding pull request. Feel free to reopen at anytime
