### ISSUE TITLE
Ahammad Shawki <@ahammadshawki8>

### ISSUE THREAD

**Issue by ahammadshawki8** [EddieHubCommunity/awesome-github-profiles#193]
![screenshot-github com-2020 12 19-18_17_59](https://user-images.githubusercontent.com/56157819/102689296-26f9e080-4227-11eb-9e75-08c1f2426889.png)

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one. Nice Profile btw 🚀
