### ISSUE TITLE
[OTHER] Awesome Github Profiles Page is not working

### ISSUE THREAD

**Issue by ezhil56x** [EddieHubCommunity/awesome-github-profiles#1933]
## Issue
[Awesome Github Profiles](https://eddiehubcommunity.github.io/awesome-github-profiles/) in the EddieHubCommunity is not working or broken

### Screenshot
![image](https://github.com/EddieHubCommunity/awesome-github-profiles/assets/103899034/65d0130c-6764-480f-832c-0df71e1c7e41)

![image](https://github.com/EddieHubCommunity/awesome-github-profiles/assets/103899034/3f60ac29-dbc4-468f-a604-98f8cada7649)

**Comment by schmelto** [comment]
thanks for raising we will track this issue in #1943
