### ISSUE TITLE
awesome-github-profiles Page NOT FOUND (404). Basically its due to either incorrect homepage Url in Package.json or incorrectly Maped Profile Section.

### ISSUE THREAD

**Issue by ultimate-disturbing-element** [EddieHubCommunity/awesome-github-profiles#1938]
### Profile screenshot

![image](https://github.com/EddieHubCommunity/awesome-github-profiles/assets/42346859/e38ba9fa-36d3-4139-b693-9c0f3e68b980)

**Comment by schmelto** [comment]
thanks for raising. we will track this issue in #1943
