### ISSUE TITLE
[PROFILE ADDITION] <ABHINAV RAI>

### ISSUE THREAD

**Issue by ultimate-disturbing-element** [EddieHubCommunity/awesome-github-profiles#1939]
### Profile screenshot

![github com_ultimate-disturbing-element](https://github.com/EddieHubCommunity/awesome-github-profiles/assets/42346859/785453f4-e906-4d12-89eb-4e6795d396f0)

**Comment by schmelto** [comment]
closing. there was no corresponding pull request. Feel free to reopen at anytime
