### ISSUE TITLE
[PROFILE ADDITION] <Elisio Massaqui>

### ISSUE THREAD

**Issue by elisioMassaqui** [EddieHubCommunity/awesome-github-profiles#1949]
### Profile screenshot

![WhatsApp Image 2023-11-16 at 21 59 09](https://github.com/EddieHubCommunity/awesome-github-profiles/assets/145590545/ea17e4d9-b040-4429-afcd-571358d85a63)

**Comment by schmelto** [comment]
closing. there was no corresponding pull request. Feel free to reopen at anytime
