### ISSUE TITLE
[DEVELOPER] <Mahima Bhardwaj>

### ISSUE THREAD

**Issue by YOGINIMAHIMA1** [EddieHubCommunity/awesome-github-profiles#1965]
### Profile screenshot

[
![github screenshot](https://github.com/EddieHubCommunity/awesome-github-profiles/assets/90374311/ef522a73-ad68-4e3f-9853-5411acc59f82)
](url)

**Comment by schmelto** [comment]
closing. there was no corresponding pull request. Feel free to reopen at anytime
