### ISSUE TITLE
[PROFILE ADDITION] <Amit kumar singh>

### ISSUE THREAD

**Issue by Amitkumarsingh27** [EddieHubCommunity/awesome-github-profiles#1974]
### Profile screenshot

![Levi Ackerman](https://github.com/EddieHubCommunity/awesome-github-profiles/assets/88762645/26b185b5-00bc-436c-87dc-9d92d27844b4)

**Comment by schmelto** [comment]
closing. there was no corresponding pull request. Feel free to reopen at anytime
