### ISSUE TITLE
[PROFILE ADDITION] <Oyindamola Abolaji>

### ISSUE THREAD

**Issue by oyin-systems** [EddieHubCommunity/awesome-github-profiles#1987]
### Profile screenshot

Profile screenshot
![screencapture-github-oyin-systems-2024-06-05-16_49_41](https://github.com/EddieHubCommunity/awesome-github-profiles/assets/78956440/23b0ef0c-7ed7-4dfc-ad0c-e62dd67fd24f)

**Comment by Gokilp** [comment]
cool
