### ISSUE TITLE
Dedar Alam

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/awesome-github-profiles#21]
<img width="1289" alt="Screenshot 2020-07-23 09 22 27" src="https://user-images.githubusercontent.com/624760/88265854-1f5cfc80-ccc6-11ea-8951-1acfd99eb8d2.png">

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one.
