### ISSUE TITLE
Prettier Github actions fails on kebab-case branches

### ISSUE THREAD

**Issue by AllanRegush** [EddieHubCommunity/awesome-github-profiles#211]
The prettier action cannot checkout kebab-case branches. Maybe complete a pull request on the action repo?

**Comment by eddiejaoude** [comment]
I have put a `bug` label on this, thank you for raising 👍

**Comment by AllanRegush** [comment]
#319 has a screenshot of the error.

**Comment by krishguptadev** [comment]
Is this still an issue? Have made PRs with branches named like `patch-1`, but didn't got any failing action for the reason.
