### ISSUE TITLE
Vincent Villafuerte

### ISSUE THREAD

**Issue by vinzvinci** [EddieHubCommunity/awesome-github-profiles#215]
![githubvinzvinci98](https://user-images.githubusercontent.com/73097560/103608126-91b05900-4f55-11eb-84af-d30f20d9332c.png)

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one. Nice Profile btw 🚀

**Comment by schmelto** [comment]
yeyy its @vinzvinci 🎉

**Comment by vinzvinci** [comment]
Lol, thanks @schmelto, my profile isn't updated here. Is it okay if I request new PR again and just edit this issue 🤔

**Comment by schmelto** [comment]
sure @vinzvinci

**Comment by vinzvinci** [comment]
Updated GitHub profile:
![image](https://user-images.githubusercontent.com/73097560/117130491-b49f2c80-add2-11eb-90bb-a04331c96a4b.png)
