### ISSUE TITLE
Max Bridgland

### ISSUE THREAD

**Issue by M4cs** [EddieHubCommunity/awesome-github-profiles#24]
Is it okay to nominate myself? 

![image](https://user-images.githubusercontent.com/34947910/88422301-0765a580-cdb8-11ea-82f9-1728f5bdeefb.png)

**Comment by eddiejaoude** [comment]
Oh awesome, yes it is 👍

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one.
