### ISSUE TITLE
Filippo Fonseca

### ISSUE THREAD

**Issue by filippo-fonseca** [EddieHubCommunity/awesome-github-profiles#244]
<img width="1440" alt="Screen Shot 2021-01-14 at 12 28 20" src="https://user-images.githubusercontent.com/48065878/104632919-feb5a400-5663-11eb-8dd0-b05cfd377158.png">
<img width="489" alt="Screen Shot 2021-01-14 at 12 28 50" src="https://user-images.githubusercontent.com/48065878/104632959-0ffeb080-5664-11eb-88ca-e5515a3f10be.png">

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one. Nice Profile btw 🚀
