### ISSUE TITLE
Connect 4 in a github profile 

### ISSUE THREAD

**Issue by alrifay** [EddieHubCommunity/awesome-github-profiles#25]
@JonathanGin52
 
![image](https://user-images.githubusercontent.com/19517534/88440875-9225bf00-ce0f-11ea-8c0f-de5528f8c9c2.png)

**Comment by eddiejaoude** [comment]
Looks good, thanks @alrifay for sharing 👍

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one.
