### ISSUE TITLE
Jaskeerat Singh

### ISSUE THREAD

**Issue by Jassi10000** [EddieHubCommunity/awesome-github-profiles#265]
![20210120_124159](https://user-images.githubusercontent.com/64856348/105141728-9f520b00-5b1f-11eb-924f-d87a5ac8e9f0.jpg)

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one. Nice Profile btw 🚀

**Comment by Jassi10000** [comment]
ok no issues , 
Thanks @schmelto
