### ISSUE TITLE
[FEAT] Update links of some (or all) GitHub profiles

### ISSUE THREAD

**Issue by alphaX86** [EddieHubCommunity/awesome-github-profiles#271]
Hi there! 👋 
I came across this repo after I joined this org to see some awesome README templates. But turns out that some didn't update their profile links in `data.json` which in turn appears the redirect link as `https://github.com/undefined`. YEP! It's a 404 error page! So, I thought I can report this so no one will do this mistake ever again.

P.S: If this issue is brought already, then kindly close this one. Thanks!

**Comment by eddiejaoude** [comment]
@alphaX86 did you mean to close this?

**Comment by alphaX86** [comment]
@eddiejaoude not exactly. But I just want to convey this issue so that new comers won't make the mistake of not adding the links in `data.json`. Well I can reopen again if you want me to do so. It's just a message in fact. Plus, it's been a week since I opened , so yeah.

**Comment by eddiejaoude** [comment]
Oh I see, hmm, if it can be left open for the moment and hopefully some can fix it. 

Would you be able to add an example with links to the line in the files, that will make it easier for someone to fix

**Comment by alphaX86** [comment]
Well, I'll do that for sure 👍

**Comment by alphaX86** [comment]
This PR seems really good @AllanRegush
