### ISSUE TITLE
Vatsal Kesarwani

### ISSUE THREAD

**Issue by plazzy99** [EddieHubCommunity/awesome-github-profiles#281]
![Screenshot from 2021-01-28 18-03-42](https://user-images.githubusercontent.com/48295138/106139911-0f9e0380-6194-11eb-9558-56ff97b53c94.png)

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one. Nice Profile btw 🚀
