### ISSUE TITLE
Hariharan Balasubramanian

### ISSUE THREAD

**Issue by HariAcidReign** [EddieHubCommunity/awesome-github-profiles#288]
![GithubHH](https://user-images.githubusercontent.com/58134096/106390118-dd4b0b00-640c-11eb-8246-7a7c45476ecb.png)

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one. Nice Profile btw 🚀

**Comment by HariAcidReign** [comment]
I didn't realize that I added my profile 2x. Got the most recent one merged, so this one was lying inactive. Thanks for closing, and glad you like my profile! 🥂
