### ISSUE TITLE
Aditya Oberai

### ISSUE THREAD

**Issue by adityaoberai** [EddieHubCommunity/awesome-github-profiles#304]
![image](https://user-images.githubusercontent.com/31401437/106563296-974b8f80-6551-11eb-8753-a13ea9e944c2.png)

**Comment by varghesejose2020** [comment]
awesome profile @adityaoberai

**Comment by adityaoberai** [comment]
Thanks a lot @varghesejose2020 😄

**Comment by varghesejose2020** [comment]
:thumbsup:

**Comment by ayush-09** [comment]
👍

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one. Nice Profile btw 🚀

**Comment by adityaoberai** [comment]
Thanks a lot @schmelto 😄

**Comment by schmelto** [comment]
Have to admit I really like the badges design 😃

**Comment by adityaoberai** [comment]
They're really nice 😃 
You can make yours too using [shields.io](https://shields.io/) 🙌
