### ISSUE TITLE
Bug: Broken Prettier Lint Check in GitHub Actions

### ISSUE THREAD

**Issue by roaldnefs** [EddieHubCommunity/awesome-github-profiles#319]
It looks like the checkout step in the **Prettier Lint check** in the GitHub Actions Workflow is broken. 

I was able to pass the Prettier Lint when making a PR directly from the `main` branch (#318, but in my original PR (#316) I a source branch called `add-profile` which causes an error in the checkout step of the Prettier Lint check.

Looks like #314 is also running into the same issue.

Screenshot of the error in #316, as is now hard to find the logging due to the PR being closed:
![GitHub Actions error](https://user-images.githubusercontent.com/6523325/107003123-918dbe00-678c-11eb-878e-1d1455956336.png)

**Comment by AllanRegush** [comment]
Thank you for creating this issue @roaldnefs. :+1:  But I've already raised this #211.

I will close as duplicate and reference this issue.

**Comment by eddiejaoude** [comment]
Thank you both 👍
