### ISSUE TITLE
Ibtihel Ouni

### ISSUE THREAD

**Issue by Ibtihel-ouni** [EddieHubCommunity/awesome-github-profiles#338]
![image](https://user-images.githubusercontent.com/58151963/107116883-97f86480-6876-11eb-8382-fc1c6ce06403.png)

**Comment by eddiejaoude** [comment]
@Ibtihel-ouni your readme is great 👍 I like the waving gif photo 🤓

**Comment by Ibtihel-ouni** [comment]
Thank you @eddiejaoude  , I appreciate it a lot :smile:

**Comment by eddiejaoude** [comment]
You are welcome 🤓

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one. Nice Profile btw 🚀
