### ISSUE TITLE
Dynamically changing vote count for each showcased readme

### ISSUE THREAD

**Issue by anuraghazra** [EddieHubCommunity/awesome-github-profiles#34]
We can use Github API & fetch each issue's reactions count to calculate the vote of each readme showcased in readme.md and use a github action to update the docs with dynamic vote counts.

**Comment by eddiejaoude** [comment]
Nice 👍 

Maybe we move the data to a json file and a GitHub Action can create the README markdown as well as order them by reaction count?

**Comment by krishguptadev** [comment]
> Nice 👍
> 
> Maybe we move the data to a json file and a GitHub Action can create the README markdown as well as order them by reaction count?

@eddiejaoude I have a PR for sorting by name https://github.com/EddieHubCommunity/awesome-github-profiles/pull/782, I could update it to use reactions. But I think alphabetical order was requested a long time (#4 #661 
and more.)
