### ISSUE TITLE
Brenda Michelle

### ISSUE THREAD

**Issue by BrendaMichellle** [EddieHubCommunity/awesome-github-profiles#353]
<img width="1280" alt="Screen Shot 2021-02-09 at 9 20 53 PM" src="https://user-images.githubusercontent.com/52740973/107423676-e890eb80-6b1c-11eb-8e72-2f15c48056a5.png">

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one. Nice Profile btw 🚀
