### ISSUE TITLE
Add Me to EddieHubCommunity 

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [EddieHubCommunity/awesome-github-profiles#393]
I really want to join the Eddie hub community. Kindly add me in the organisation.

**Comment by eddiejaoude** [comment]
I will close this as the issue has been created on the `support` repo, sorry for the confusion https://github.com/EddieHubCommunity/support/issues/1063#event-4427473978

We welcome any suggestions how to make this clearer for new people.
