### ISSUE TITLE
Creating a website

### ISSUE THREAD

**Issue by rohank2502** [EddieHubCommunity/awesome-github-profiles#405]
Rather than keeping it in our read me let's host this on GitHub pages! We can use the iframe tag to view the present version of his profile rather than screenshot

**Comment by rohank2502** [comment]
> 
> 
> Rather than keeping it in our read me let's host this on GitHub pages! We can use the iframe tag to view the present version of his profile rather than screenshot

If its a good idea can go with separate repository

**Comment by Vyvy-vi** [comment]
I think we could eventually connect this with our mai website.
(There has been discussions on having a hackathons section)

For now, I guess we can just activate GitHub pages in the repo, and that should render a page for the README

**Comment by rohank2502** [comment]
> or now, I guess we can just activate GitHub pages in the repo, and that should render a page for the README

Yes that can be done

**Comment by eddiejaoude** [comment]
I think the website could read this json file and display it as a separate page on the website and could even select a few at random for the homepage

**Comment by rohank2502** [comment]
> I think the website could read this json file and display it as a separate page on the website and could even select a few at random for the homepage

https://rohank2502.github.io/EddieHub_Members/

**Comment by eddiejaoude** [comment]
Cool 👍
