### ISSUE TITLE
Bryson Mundia

### ISSUE THREAD

**Issue by Bryson69** [EddieHubCommunity/awesome-github-profiles#423]
![Bryson Mundia](https://user-images.githubusercontent.com/62892010/113416945-06ffbe80-93cb-11eb-803e-aed8b7d193ff.png)

**Comment by Bryson69** [comment]
What Do you think?

**Comment by HariAcidReign** [comment]
@AllanRegush image displayed seems to be incorrect (just noticed it)

**Comment by AllanRegush** [comment]
Good Catch @HariAcidReign
