### ISSUE TITLE
Add Bryson Mundia

### ISSUE THREAD

**Issue by Bryson69** [EddieHubCommunity/awesome-github-profiles#427]
![Bryson Mundia](https://user-images.githubusercontent.com/62892010/113439186-ba2fde00-93f2-11eb-8042-bdb111493c18.png)

**Comment by Bryson69** [comment]
The correct Image

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one. Nice Profile btw 🚀
