### ISSUE TITLE
Yash Sehgal

### ISSUE THREAD

**Issue by yashsehgal** [EddieHubCommunity/awesome-github-profiles#429]
![image](https://user-images.githubusercontent.com/62352288/113475867-6aeeb980-9495-11eb-86be-bfa0085a6f48.png)

**Comment by Jaspreet099** [comment]
nice profile

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one. Nice Profile btw 🚀

**Comment by yashsehgal** [comment]
Thanks @schmelto :)
