### ISSUE TITLE
Automating scrapping GitHub profile

### ISSUE THREAD

**Issue by jai-dewani** [EddieHubCommunity/awesome-github-profiles#438]
Instead of saving static images, if we could just store the usernames of all the folks and use a script to generate a screenshot of their profile periodically (once a week/month) using GitHub action, wouldn't that be cool?

**Comment by Rahma-AlWadhahi** [comment]
That would be great. It will ensure that the profile images are updated!
However, I think that it would be best to replace the screenshots and store them by username. I mean that the screenshot name format would be like `Rahma-AlWadhahi.png`. This way we can map each of them to the right cell location.

**Comment by eddiejaoude** [comment]
Great idea 👍 , I think we could do it as part of the GitHub Action with a headless web screen capture in node  🤓

**Comment by JatinAgrawal94** [comment]
Hello folks, I want to work on this issue, can you guide me on how to get started?

**Comment by schmelto** [comment]
duplicate with #52

**Comment by schmelto** [comment]
> Hello folks, I want to work on this issue, can you guide me on how to get started?

you can take a look at #52 otherwise we can discuss this in the discord server

**Comment by schmelto** [comment]
closing this due to duplicate with #52
