### ISSUE TITLE
Ujjwal Gupta 

### ISSUE THREAD

**Issue by UG-SEP** [EddieHubCommunity/awesome-github-profiles#453]
Hey @schmelto ,
I wanted to add my profile 
[Click me to see Ujjwal's Profile😃](https://github.com/UG-SEP)
If you like it please assign me to do it 
Thanks

**Comment by schmelto** [comment]
Hey @UG-SEP.
Unfortunately I can not assign you due I have no write access to the repo. But lucky for us this is not necessary :) You can add yourself by following the steps shown in the readme [here](https://github.com/EddieHubCommunity/awesome-github-profiles#to-add-your-github-profile) just copy a screenshot of your profile and add it here in this issue as comment or update your description above. Than you can fork the repository and follow the above mention steps in the readme. By creating a PR the community and probably myself will approve your changes and the PR will be merged. 🚀 Hope this will help you :)

**Comment by UG-SEP** [comment]
> Hey @UG-SEP.
> Unfortunately I can not assign you due I have no write access to the repo. But lucky for us this is not necessary :) You can add yourself by following the steps shown in the readme [here](https://github.com/EddieHubCommunity/awesome-github-profiles#to-add-your-github-profile) just copy a screenshot of your profile and add it here in this issue as comment or update your description above. Than you can fork the repository and follow the above mention steps in the readme. By creating a PR the community and probably myself will approve your changes and the PR will be merged. 🚀 Hope this will help you :)
> 
> Onle thing in addition take a look at you Readme
> ![Screenshot_20210424_045934.jpg](https://user-images.githubusercontent.com/30869493/115945047-f1f1e900-a4b9-11eb-93b9-e0909f6e1274.jpg)
> Think the hype there was not intended to be here :D
> 
> I just saw you forked the repo already https://github.com/UG-SEP/awesome-github-profiles make sure that you pull the latest changes from origin by configuring the remote upstream or pulling the changes from origin. If you need any help there feel free to ask the community/me.

changes done as you told 
Thanks for telling me

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one. Nice Profile btw 🚀
