### ISSUE TITLE
Kaiwalya Koparkar

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [EddieHubCommunity/awesome-github-profiles#475]
![My profile](https://user-images.githubusercontent.com/53310847/117104479-d3350180-ad99-11eb-8152-2afaff67fe04.png)

**Comment by schmelto** [comment]
I`m closing this issue due the related PR is merged and people can still vote for it.

**Comment by kaiwalyakoparkar** [comment]
Thank you so much @schmelto, Sorry I forgot to link this issue in the PR :sweat_smile:

**Comment by schmelto** [comment]
no problem @kaiwalyakoparkar
