### ISSUE TITLE
Create a YouTube video showing your favourite vs code shortcuts

### ISSUE THREAD

**Issue by mikeysan** [EddieHubCommunity/awesome-github-profiles#49]
During the live stream of GitHub actions you used a number of impressive shortcuts while using vs code. A few of us would like to see a video on some of these shortcuts.

I even have a nice title for you: Title: Eddie's favourite VS Code shortcuts (ps. Thanks AiXing)

Also, please do not forget to include keystroke displays for both mac os and Windows; e.g. <option> + Up/Down and whatever that will be on Windows.

**Comment by Shubham714** [comment]
That's a great idea.

**Comment by schmelto** [comment]
I think this would be better in the support repo

https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=enhancement&template=ideas.md&title=

I close this one here :)

**Comment by eddiejaoude** [comment]
Btw did a new issue get created on the `support` repo? I cannot remember the shortcuts I used, but sounds like a good video 👍
