### ISSUE TITLE
aminos 🇮🇳 

### ISSUE THREAD

**Issue by amino19** [EddieHubCommunity/awesome-github-profiles#499]
![github-profile](https://user-images.githubusercontent.com/75872316/118384765-6dad0480-b626-11eb-85ce-a6af24c19181.png)

**Comment by schmelto** [comment]
Hey @amino19 if you want your profile visible in the readme please open a pull request with the necessary changes.

## To add your github profile

1. Create an issue, with the title as your name, and in the description put a screenshot of the customised GitHub profile page (copy the generated image url, this will be needed in the next step)

2. Fork the project

3. In `data.json` add your own object to the end of the file, your entry should be similar to this example:

```typescript
{
    "name": "Eddie Jaoude",
    "githubUsername": "eddiejaoude",
    "imageUrl": "https://user-images.githubusercontent.com/624760/91057573-48531300-e61f-11ea-9e13-2d7384e42000.png",
    "issueNumber": 66
}
```

**Note** : Please do not edit anything below `<!--START_SECTION:data-section-->` in `README.MD` our [GitHub Action](https://github.com/EddieJaoudeCommunity/gh-action-community) will make the necessary changes for you.

4. Create a Pull Request to add the changes to this Repository. Please change the title to `add your-username` and in the description add `resolve #issueNumber`

**Comment by amino19** [comment]
Ya sure, thanks for the permit, I just want someone to shoot here!
