### ISSUE TITLE
Why did the Github Action was not triggered 🤔

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/awesome-github-profiles#516]
Why did the Github Action was not triggered 🤔 

_Originally posted by @schmelto in https://github.com/EddieHubCommunity/awesome-github-profiles/pull/515#issuecomment-841795369_

**Comment by namangupta1399** [comment]
Check this out: https://www.githubstatus.com/

**Comment by schmelto** [comment]
> Check this out: https://www.githubstatus.com/

Yes this could be the issue thx I will take a look later that day

**Comment by schmelto** [comment]
Issue is fixed now
