### ISSUE TITLE
Astha Nayak

### ISSUE THREAD

**Issue by nayakastha** [EddieHubCommunity/awesome-github-profiles#526]
![github profile](https://user-images.githubusercontent.com/58568514/119360619-6cd03e80-bcc8-11eb-8fec-699c31daac61.PNG)

**Comment by schmelto** [comment]
Hey @nayakastha the image link in the code is broken can you adjust it?
If you need any help please let us know :)

**Comment by nayakastha** [comment]
> Hey @nayakastha the image link in the code is broken can you adjust it?
> If you need any help please let us know :)
> 
> Image link in data.json: https://user-images.githubusercontent.com/58568514/119360619-6cd03e80-bcc8-11eb-8fec-699c31daac61.png
> 
> ![image](https://user-images.githubusercontent.com/30869493/119949584-4d703480-bf9a-11eb-9835-82e157860138.png)
> 
> Image link that should work: https://user-images.githubusercontent.com/58568514/119360619-6cd03e80-bcc8-11eb-8fec-699c31daac61.PNG
> 
> Maybe its only borken for me idk :D

Hey! Thanks for bringing it to my notice. I will fix it asap.

**Comment by nayakastha** [comment]
@schmelto could you review and merge the Pull Request #533

**Comment by schmelto** [comment]
> @schmelto could you review and merge the Pull Request #533

thanks for adjusting 🚀
