### ISSUE TITLE
Kamlesh_Joshi

### ISSUE THREAD

**Issue by kamleshjoshi8102** [EddieHubCommunity/awesome-github-profiles#558]
![image](https://user-images.githubusercontent.com/72374645/123034023-67b8f900-d406-11eb-829a-6df34ba91852.png)

**Comment by kamleshjoshi8102** [comment]
I have not received invitation link for the Organisation @schmelto

**Comment by starlightknown** [comment]
@kamleshjoshi8102 you have to raise an issue in support repo with label invite me to the organisation, you'll get invited

**Comment by kamleshjoshi8102** [comment]
> @kamleshjoshi8102 you have to raise an issue in support repo with label invite me to the organisation, you'll get invited

okay thanks @starlightknown 
: )
