### ISSUE TITLE
[README] Need to Update aminos 🇮🇳

### ISSUE THREAD

**Issue by amino19** [EddieHubCommunity/awesome-github-profiles#582]
**Suggested changes:**
Need to update my `user profile` image at `README.md` :slightly_smiling_face: 

Previous issue #499

**Comment by starlightknown** [comment]
Hey take a screenshot of your profile and upload it in the issue. Copy the url and add other details in data.json file

**Comment by amino19** [comment]
@schmelto : I think that's ready to take it over your end! :rocket:
