### ISSUE TITLE
Create a GitHub Action to automatically sort profiles alphabetically

### ISSUE THREAD

**Issue by BOLT04** [EddieHubCommunity/awesome-github-profiles#6]
This action could run each commit, or before the PR gets merged. This way we can correct it automatically without asking more work on the contributor.

**Comment by eddiejaoude** [comment]
Interesting! Really this could be done in a GitHub Action? 😱 How would that work, run as a function?

**Comment by BOLT04** [comment]
I remember seeing another issue related to this sorting ([here](https://github.com/ErikCH/DevYouTubeList/issues/85)), but it might be more complicated than what I'm thinking about.
We'd have to dig in and investigate more on how to do this.
