### ISSUE TITLE
Repo need more internet bandwidth to load

### ISSUE THREAD

**Issue by TheSlimCoder** [EddieHubCommunity/awesome-github-profiles#618]
Guy's this repo need more internet bandwidth and take more time to load README.md successfully on slow internet.
I was thinking to do a change related to README.md we can create a new file using English Alphabets and separate individuals using Alphabets.

**Comment by Panquesito7** [comment]
I agree; this would take a lot to load on slow Internet. My suggestion is similar to your suggestion, but it'd be better if we make another file for all the profiles currently listed in `README.md` (named `profiles.md`, or something like that).

**Comment by MRslimcoder** [comment]
I think we should separate md's from A-Z can show first two user's within each.

**Comment by MRslimcoder** [comment]
Okay so I will try to send a PR as soon as possible.

**Comment by krishguptadev** [comment]
Hey there @TheSlimCoder do you need any help? 🙂

**Comment by TheSlimCoder** [comment]
@schmelto I'm not currently working on this issue. Maybe you can try it and send a PR.

**Comment by TheSlimCoder** [comment]
@krishguptadev We both can work together so first discuss how we gonna do it.

**Comment by Panquesito7** [comment]
I think this was already fixed: there's a separate `profiles.md` file where all the profiles are stored, so it shouldn't cause a major issue unless you check that file.

**Comment by TheSlimCoder** [comment]
@Panquesito7 should we further divide the profiles in alphabetical order and create seperate md files?

**Comment by krishguptadev** [comment]
> @Panquesito7 should we further divide the profiles in alphabetical order and create seperate md files?

The project is shifting to nextjs, thus shouldn't be a issue now, issue can be closed.

**Comment by TheSlimCoder** [comment]
@krishguptadev are you sure if we switch to next.js this issue will not arise?

**Comment by krishguptadev** [comment]
> @krishguptadev are you sure if we switch to next.js this issue will not arise?

I think so, there are no images on the readme now, that solves the issue itself
