### ISSUE TITLE
Suggestion : make a GitHub Pages or JS.org website for awesome-github-profiles

### ISSUE THREAD

**Issue by AvidCoder101** [EddieHubCommunity/awesome-github-profiles#623]
This is just an idea, and it doesn't have to be certain. I was just thinking that maybe this website is worthy of being hosted by Github or JS.org with a Jekyll theme using simply the README.md. If members agree with this, we would probably have to tweak the README.md around a bit to make it more clearer on where to contribute. Please send any feedback or your thoughts on this. Thanks (:

**Comment by Panquesito7** [comment]
That sounds like a great idea! I don't really know too much about Web Development. I can help a bit, though, not that much.

**Comment by MRslimcoder** [comment]
@AvidCoder101 Great idea we should have a GitHub page <3

**Comment by Panquesito7** [comment]
We could make a simple page like this one https://minetest-mods.github.io/

**Comment by MRslimcoder** [comment]
> We could make a simple page like this one https://minetest-mods.github.io/

Cool 😎

**Comment by AvidCoder101** [comment]
I think in order to do this though one of the admins would have to set up the Github pages first

**Comment by AvidCoder101** [comment]
After they did, they could select a theme from Jekyll to style it around, or if people wanted to, they could use html to create one of their own style

**Comment by MRslimcoder** [comment]
> I think in order to do this though one of the admins would have to set up the Github pages first

Yeah! maybe @eddiejaoude can help us.

**Comment by MRslimcoder** [comment]
> After they did, they could select a theme from Jekyll to style it around, or if people wanted to, they could use html to create one of their own style

Use of styling theme is good option.

**Comment by Panquesito7** [comment]
> We could make a simple page like this one https://minetest-mods.github.io/

I could start working on this one if you want, but as you said above, someone with Administrator access must enable the GitHub Pages in this repository.

**Comment by MRslimcoder** [comment]
@Panquesito7 @AvidCoder101 count me in. 

also js.org don't promote github pages with md files, they need a proper HTML, CSS, JS website on repository to be connected with GitHub pages then CNAME of js.org will work. so don't try JS.org we use pure github pages with custom domain (If possible).

**Comment by MRslimcoder** [comment]
Without custom domain our domain will be:

https://EddieHubCommunity.github.io/awesome-github-profiles

By using custom domain:

https://minetest-mods.github.io

**Comment by Panquesito7** [comment]
I'll try to work on this next week. I'll let you know of any updates. Thanks. 🙂

**Comment by Panquesito7** [comment]
Sorry for the delay. I'm working on it now. 😄

**Comment by KukretiShubham** [comment]
@Panquesito7 Interesting idea. Would like to work with you. What you say?

**Comment by Panquesito7** [comment]
That'd be great, thanks! Currently, I am using a theme provided by Jekyll. I also want to make the profiles be pushed to a file named `profiles.md`, which is working but needs some customization. You can contact me via Discord if you like. 🙂

**Comment by CodingSpecies** [comment]
**I am not sure how, but this is just an idea:**
- Maybe we should find a way to try and get a functionality to allow voting each profile on the website?
- Or we could create something like a leader board?
- Perhaps, the website is made first, displaying each profile and then we figure this out? Thanks.

**Comment by eddiejaoude** [comment]
Hey all, sorry for my slow reply, I am behind in GitHub notifications. I have enabled GitHub Pages for the branch `gh-pages`

<img width="1665" alt="Screenshot 2021-08-16 at 06 22 47" src="https://user-images.githubusercontent.com/624760/129514975-e8d19959-d4ec-46ef-849c-c43dbb7eca5e.png">

**Comment by AvidCoder101** [comment]
Thanks @eddiejaoude!

**Comment by eddiejaoude** [comment]
Great collaboration everyone 💥

**Comment by CodingSpecies** [comment]
this is the url of the website: https://eddiehubcommunity.github.io/awesome-github-profiles/
thanks.

**Comment by Panquesito7** [comment]
I'll make a pull request to improve the page soon. Thanks for enabling GitHub Pages, though! 😄

**Comment by Panquesito7** [comment]
What do you think about it? React with 👍 if you like it. If there's something you don't like, please let me know.

https://panquesito7.github.io/awesome-github-profiles

Currently, I'm working on making the GitHub Action push to `profiles.md` instead of `README.md`; but I'm having some problems. I already asked for help. I hope it doesn't take long. Thanks though.

**Comment by CodingSpecies** [comment]
This is something we could work on after the website is successful:
To navigate easily to each profile, I will try to find a way to add an alphabetical contents table, and organise everyone's profiles alphabetically, like this: 

### Go to Profiles:
- [A]()                                                               
-  [B]()
etc.

it might be a bit difficult trying to organise it all, but if you all agree, maybe I could try to find a way to do this? If you don't approve, then also please say. thanks.

**Comment by qwe123coder** [comment]
the :100: is not being showed in the https://eddiehubcommunity.github.io/awesome-github-profiles/
![image](https://user-images.githubusercontent.com/72848513/130195365-6083e759-f50c-487b-8f3c-6a70632041bc.png)

**Comment by AvidCoder101** [comment]
Thanks for spotting that @qwe123coder. I will try to fix it (:

**Comment by AvidCoder101** [comment]
@qwe123coder Please make a new issue and then I would be happy to fix it with a Pull Request. Thank you (:

**Comment by CodingSpecies** [comment]
> the 💯 is not being showed in the https://eddiehubcommunity.github.io/awesome-github-profiles/
> ![image](https://user-images.githubusercontent.com/72848513/130195365-6083e759-f50c-487b-8f3c-6a70632041bc.png)

#659

**Comment by schmelto** [comment]
https://eddiehubcommunity.github.io/awesome-github-profiles/

**Comment by CodingSpecies** [comment]
@schmelto do you or any other maintainer have access to adding the website link in the about section? 
![image](https://user-images.githubusercontent.com/70807500/144744368-c8073542-9093-4a20-b35e-85f912096e76.png)
Thank you

**Comment by schmelto** [comment]
> @schmelto do you or any other maintainer have access to adding the website link in the about section? 
> ![image](https://user-images.githubusercontent.com/70807500/144744368-c8073542-9093-4a20-b35e-85f912096e76.png)
> Thank you

#886

**Comment by AvidCoder101** [comment]
Great work everybody, thanks @Panquesito7 for making this PR and @eddiejaoude for confirming it, and thanks to everyone who has contributed too 😊
