### ISSUE TITLE
add qwe123pro

### ISSUE THREAD

**Issue by qwe123coder** [EddieHubCommunity/awesome-github-profiles#629]
https://github.com/qwe123coder

**Comment by qwe123coder** [comment]
readme.md to big to fit in one img 
![image](https://user-images.githubusercontent.com/72848513/127673630-59e2eadc-86b9-43c6-baf4-f497ccfdb6ab.png)
![image](https://user-images.githubusercontent.com/72848513/127673654-cefaa8cc-ec05-42bb-a23f-d75fc569fb64.png)
![image](https://user-images.githubusercontent.com/72848513/127673670-38927bc9-d913-4a6a-baf5-d930787bc4b8.png)
![image](https://user-images.githubusercontent.com/72848513/127673724-63fb19e3-e9af-49d0-b1be-2d97861e0343.png)
![image](https://user-images.githubusercontent.com/72848513/127673790-958db388-2825-4d9e-a055-97fbfc1928ed.png)

**Comment by Panquesito7** [comment]
I would suggest only taking a screenshot of some part of it, not completely or multiple images like I did. 🙂

**Comment by adityagarde** [comment]
Hi @qwe123coder 
Use any chrome plugin to take a full-screen screenshot.
Ex - https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl
Hope it helps!

**Comment by qwe123coder** [comment]
![screencapture-github-qwe123coder-2021-08-17-09_47_51](https://user-images.githubusercontent.com/72848513/129662985-fe7fd935-9ba3-4c54-ad55-a114e5db303d.png)

**Comment by CodingSpecies** [comment]
@qwe123coder, I think you should crop from where is says popular repositories, to leave the readme by itself.

**Comment by Panquesito7** [comment]
I would recommend more of an image like this.

![image](https://user-images.githubusercontent.com/51391473/129775827-5d94ffc7-81bc-4364-9e08-a936030e6006.png)

**Comment by krishguptadev** [comment]
@qwe123coder I think you need to make a PR to add your profile 🤔

**Comment by qwe123coder** [comment]
go on make :)
