### ISSUE TITLE
Add VasudevJaiswal

### ISSUE THREAD

**Issue by VasudevJaiswal** [EddieHubCommunity/awesome-github-profiles#641]
<h3>

{ "name": "Vasudev Jaiswal",

    "githubUsername": "VasudevJaiswal",

    "imageUrl": "https://user-images.githubusercontent.com/85981735/129255772-5bac726e-d98e-4eb4-8c9f-c2206b72c976.png",

    "issueNumber": 630 }
</h3>

***

<h3> Here My github Profile Screenshot </h3>

***
![VasudevJaiswal](https://user-images.githubusercontent.com/85981735/129255772-5bac726e-d98e-4eb4-8c9f-c2206b72c976.png)

**Comment by VasudevJaiswal** [comment]
Dear EddieHubCommunity Why are you not pust my issue

**Comment by Cahllagerfeld** [comment]
You could probably raise a PR for that (:

**Comment by Panquesito7** [comment]
You need to fork this repository, implement your changes, and make a pull request. If you need any help, let me know. 🙂

**Comment by VasudevJaiswal** [comment]
How to find a github profile pic link

**Comment by CodingSpecies** [comment]
@VasudevJaiswal :
 - you push your work.
 - Get screenshot of profile.
 -  Then you upload the image.
 -  And github changes your image in to a link, which will be like `https://avatars.githubusercontent.com/profileimg`

**Comment by CodingSpecies** [comment]
The url of yours is `https://user-images.githubusercontent.com/85981735/129035493-40b5ed91-fe64-48ad-b1a6-fcc845f83236.png`

**Comment by VasudevJaiswal** [comment]
Oh thanks bro but i change the profile screenshot with new profile pic
What I do ?

**Comment by CodingSpecies** [comment]
As the example in readme, you do this in the json file:

`{
    "name": "name",
    "githubUsername": "username",
    "imageUrl": "profile link",
    "issueNumber": num
}
`

**Comment by VasudevJaiswal** [comment]
Thank everyone bro for help 🙏

**Comment by VasudevJaiswal** [comment]
@Panquesito How to join this organisation plz tell me

**Comment by deephunt3r** [comment]
@VasudevJaiswal Hey you can use this [link](https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization ) to join! I hope it helps 😄

**Comment by VasudevJaiswal** [comment]
@deephunt3r  Thank bhai 😊
