### ISSUE TITLE
add Harkirat Singh

### ISSUE THREAD

**Issue by harkiratsm** [EddieHubCommunity/awesome-github-profiles#645]
[https://github.com/harkiratsm](url)

**Comment by Panquesito7** [comment]
Hey, @harkiratsm! You need to make a pull request to add your profile. You need to fork the repository, implement your changes, and submit a pull request. Let us know if you need any help. 🙂

**Comment by VasudevJaiswal** [comment]
@harkiratsm
1.  you push your work.
2.  Get screenshot of profile.
3.  Then you upload the image.
4.  And github changes your image in to a link, which will be like https://avatars.githubusercontent.com/profileimg

**Comment by harkiratsm** [comment]
![screencapture-github-harkiratsm-2021-08-19-15_00_21](https://user-images.githubusercontent.com/71957674/130045204-ca944c44-ba03-4937-9cc9-276f0019204b.png)

**Comment by CodingSpecies** [comment]
@harkiratsm , I think you should crop out from where it shows your pinned repos, so it leaves your readme only. thanks

**Comment by harkiratsm** [comment]
![screencapture-github-harkiratsm-2021-08-19-15_00_21](https://user-images.githubusercontent.com/71957674/130051242-25747856-913e-4613-9cc6-7384dc58d752.png)

**Comment by CodingSpecies** [comment]
Thank you @harkiratsm
