### ISSUE TITLE
Updating My Profile Name, and README.

### ISSUE THREAD

**Issue by CodingSpecies** [EddieHubCommunity/awesome-github-profiles#650]
I have updated my section, by changing my name and image url. thanks

**Comment by CodingSpecies** [comment]
![my profile](https://user-images.githubusercontent.com/70807500/129594715-ef05ecc0-720f-4b75-a507-c2afed68cf02.png)

**Comment by CodingSpecies** [comment]
#651

**Comment by schmelto** [comment]
#604
