### ISSUE TITLE
Ahamed Profile

### ISSUE THREAD

**Issue by ahamedbasha-n** [EddieHubCommunity/awesome-github-profiles#663]
![ahamed](https://user-images.githubusercontent.com/69695103/130542739-8b989683-190b-44ee-8c48-cd78b341fbc9.PNG)

**Comment by Panquesito7** [comment]
Hey, @ahamedbasha-n! To get your profile added to the list, you must fork the repository, add your profiles as explained in the [`README.md`](https://github.com/EddieHubCommunity/awesome-github-profiles#to-add-your-github-profile), make a pull request, and if all is well, we'll merge your pull request. Let me know if you need any help. 🙂

**Comment by VasudevJaiswal** [comment]
@ahamedbasha-n 

1. you push your work.
2. Get screenshot of profile.
3. Then you upload the image.
And github changes your image in to a link . 
4. You need to fork the repository, implement your changes, and submit a pull request
