### ISSUE TITLE
Mohammad Shakib

### ISSUE THREAD

**Issue by Mo-Shakib** [EddieHubCommunity/awesome-github-profiles#675]
![image](https://user-images.githubusercontent.com/50780268/131604251-f07f6811-d795-448f-a7b8-0f13b58c602f.png)

**Comment by VasudevJaiswal** [comment]
**@pravash123
1.  you push your work.
2.  Get screenshot of profile.
3.  Then you upload the image.
4.  And github changes your image in to a link, which will be like   
[Link Copy Here ](https://user-images.githubusercontent.com/50780268/131604251-f07f6811-d795-448f-a7b8-0f13b58c602f.png)

5.  Add data.json with your data. You need to fork the repository, implement your changes, and submit a pull request 🙂🎉**
