### ISSUE TITLE
Komal7209

### ISSUE THREAD

**Issue by Komal7209** [EddieHubCommunity/awesome-github-profiles#681]
![komal](https://user-images.githubusercontent.com/33154959/131914392-21e96b0f-38e2-4d3b-ad68-0c9e8d93c9d6.png)

**Comment by VasudevJaiswal** [comment]
@pravash123
1.  you push your work.
2.  Get screenshot of profile.
3.  Then you upload the image.
4.  And github changes your image in to a link, which will be like   
[Click here for link ](https://user-images.githubusercontent.com/33154959/131914392-21e96b0f-38e2-4d3b-ad68-0c9e8d93c9d6.png)

5.  Add data.json with your data. You need to fork the repository, implement your changes, and submit a pull request 🙂🎉**
