### ISSUE TITLE
Rakesh

### ISSUE THREAD

**Issue by mahatorakesh** [EddieHubCommunity/awesome-github-profiles#682]
![Mahatorakesh](https://github.com/mahatorakesh/mahatorakesh/blob/master/Screen-Shot.png)

**Comment by CodingSpecies** [comment]
@mahatorakesh , I think there is something wrong with the image url. Also, you need to create a pr with your image url.

### What to do:

- [x] Take a screenshot of your profile, up to where it says `pinned repos`.
- [x] As you just took a screenshot, just `ctrl v` it into the issue. Or, save it to your computer and then upload it to GitHub, and it will generate a custom image URL, when you copy image address.
- [x] Go to your forked copy of the repo, and go to `data.json` and add your name, paste in the image url and fill out the rest.
### Now, just open a pull request with your changes!  🎉

**Comment by mahatorakesh** [comment]
![Screen Shot 2021-09-03 at 17 45 04](https://user-images.githubusercontent.com/69909347/132004094-4b855bef-9319-456a-be0b-9530eea3dfea.png)

**Comment by VasudevJaiswal** [comment]
@mahatorakesh 
1.  you push your work.
2.  Get screenshot of profile.
3.  Then you upload the image.
4.  And github changes your image in to a link, which will be like   
[Click here for link ]https://user-images.githubusercontent.com/69909347/132004094-4b855bef-9319-456a-be0b-9530eea3dfea.png)

5.  Add data.json with your data. You need to fork the repository, implement your changes, and submit a pull request 🙂🎉**

**Comment by mahatorakesh** [comment]
I did already I guess🤔

**Comment by mahatorakesh** [comment]
![Screen Shot 2021-09-04 at 22 21 57](https://user-images.githubusercontent.com/69909347/132102357-23589224-2837-41c9-b9f6-851915edc78d.png)

**Comment by CodingSpecies** [comment]
@mahatorakesh , you have made a pull request in your own fork of the repository

**Comment by CodingSpecies** [comment]
After you commit, in your own fork, you open the pull request in the actual repo
