### ISSUE TITLE
Add rehanpunjwani

### ISSUE THREAD

**Issue by rehanpunjwani** [EddieHubCommunity/awesome-github-profiles#730]
![screencapture-github-rehanpunjwani-2021-09-25-18_03_01](https://user-images.githubusercontent.com/51391473/134791010-7e18ffeb-f5f1-4b0f-ac41-4c4bc9006485.png)

**Comment by aniket-24** [comment]
@rehanpunjwani how did u take this long screenshot of your readme.md?
Please help and tell me!

**Comment by rehanpunjwani** [comment]
> @rehanpunjwani how did u take this long screenshot of your readme.md?
> Please help and tell me!

@aniket-1812 there are many chrome extensions available that can help you take full-page screenshots.

**Comment by CodingSpecies** [comment]
@rehanpunjwani please can you only take the screenshot upto the end of the readme, up to where it says `pinned repos`. Thank you.

**Comment by CodingSpecies** [comment]
> 
> 
> @rehanpunjwani please can you only take the screenshot upto the end of the readme, up to where it says `pinned repos`. Thank you.

Actually it's ok! @Panquesito7 explained this in your pr, sorry for this @rehanpunjwani ! Thank you
