### ISSUE TITLE
can I upload my readme file here?

### ISSUE THREAD

**Issue by Gur-jot** [EddieHubCommunity/awesome-github-profiles#745]
I want to `upload` my readme file here

**Comment by Gur-jot** [comment]
`<h1 align="center">Hi 👋, I'm Gurjot Singh</h1>
<h3 align="center">I'm a student of Engineering At Poornima Group of Institution</h3>

<p align="left"> <img src="https://komarev.com/ghpvc/?username=gur-jot&label=Profile%20views&color=0e75b6&style=flat" alt="gur-jot" /> </p>

<p align="left"> <a href="https://github.com/ryo-ma/github-profile-trophy"><img src="https://github-profile-trophy.vercel.app/?username=gur-jot" alt="gur-jot" /></a> </p>

<p align="left"> <a href="https://twitter.com/gur_jot_" target="blank"><img src="https://img.shields.io/twitter/follow/gur_jot_?logo=twitter&style=for-the-badge" alt="gur_jot_" /></a> </p>

- 👨‍💻 All of my projects are available at [https://gur-jot.github.io/Gurjot-singh.github.io/](https://gur-jot.github.io/Gurjot-singh.github.io/)

- 📝 I regularly write articles on [https://medium.com/@gurjot9803](https://medium.com/@gurjot9803)

- 📫 How to reach me **gurjot9803@gmail.com**

- ⚡ Fun fact **I love to watch sci-fi stuff**

<h3 align="left">Connect with me:</h3>
<p align="left">
<a href="https://twitter.com/gur_jot_" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/twitter.svg" alt="gur_jot_" height="30" width="40" /></a>
<a href="https://linkedin.com/in/gur-jot" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="gur-jot" height="30" width="40" /></a>
<a href="https://instagram.com/_gur_jot" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/instagram.svg" alt="_gur_jot" height="30" width="40" /></a>
<a href="https://medium.com/@gurjot9803" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/medium.svg" alt="@gurjot9803" height="30" width="40" /></a>
<a href="https://www.youtube.com/c/gurjot singh" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/youtube.svg" alt="gurjot singh" height="30" width="40" /></a>
<a href="https://www.hackerrank.com/gurjot9803" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/hackerrank.svg" alt="gurjot9803" height="30" width="40" /></a>
<a href="https://www.hackerearth.com/@gurjot9803" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/hackerearth.svg" alt="@gurjot9803" height="30" width="40" /></a>
<a href="https://auth.geeksforgeeks.org/user/2020pgicagurjot45" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/geeks-for-geeks.svg" alt="2020pgicagurjot45" height="30" width="40" /></a>
<a href="https://discord.gg/#0135" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/discord.svg" alt="#0135" height="30" width="40" /></a>
</p>

<h3 align="left">Languages and Tools:</h3>
<p align="left"> <a href="https://getbootstrap.com" target="_blank"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain-wordmark.svg" alt="bootstrap" width="40" height="40"/> </a> <a href="https://www.cprogramming.com/" target="_blank"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/c/c-original.svg" alt="c" width="40" height="40"/> </a> <a href="https://www.w3schools.com/cpp/" target="_blank"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/cplusplus/cplusplus-original.svg" alt="cplusplus" width="40" height="40"/> </a> <a href="https://www.w3schools.com/css/" target="_blank"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg" alt="css3" width="40" height="40"/> </a> <a href="https://cloud.google.com" target="_blank"> <img src="https://www.vectorlogo.zone/logos/google_cloud/google_cloud-icon.svg" alt="gcp" width="40" height="40"/> </a> <a href="https://git-scm.com/" target="_blank"> <img src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg" alt="git" width="40" height="40"/> </a> <a href="https://www.w3.org/html/" target="_blank"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" width="40" height="40"/> </a> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript" target="_blank"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg" alt="javascript" width="40" height="40"/> </a> <a href="https://nodejs.org" target="_blank"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg" alt="nodejs" width="40" height="40"/> </a> <a href="https://www.php.net" target="_blank"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/php/php-original.svg" alt="php" width="40" height="40"/> </a> </p>

<p><img align="left" src="https://github-readme-stats.vercel.app/api/top-langs?username=gur-jot&show_icons=true&locale=en&layout=compact" alt="gur-jot" /></p>

<p>&nbsp;<img align="center" src="https://github-readme-stats.vercel.app/api?username=gur-jot&show_icons=true&locale=en" alt="gur-jot" /></p>

<p><img align="center" src="https://github-readme-streak-stats.herokuapp.com/?user=gur-jot&" alt="gur-jot" /></p>`

**Comment by CodingSpecies** [comment]
@Gur-jot 
### What to do:

- [x] Take a screenshot of your profile, up to where it says `pinned repos`.
- [x] As you just took a screenshot, just `ctrl v` it into the issue. Or, save it to your computer and then upload it to GitHub, and it will generate a custom image URL, when you copy image address.
- [x] Go to your forked copy of the repo, and go to `data.json` and add your name, paste in the image url and fill out the rest.
### Now, just open a pull request with your changes!  🎉

**Comment by Gur-jot** [comment]
![GurjotSingh_readme](https://user-images.githubusercontent.com/78019426/135702977-49c9edde-95bc-42da-b966-901d29567923.jpg)

**Comment by Gur-jot** [comment]
![GurjotSingh_readme](https://user-images.githubusercontent.com/78019426/135703000-f777dee5-735f-4c93-acc7-86fcce0d20a0.jpg)
