### ISSUE TITLE
Atinuke Kayode

### ISSUE THREAD

**Issue by iambami** [EddieHubCommunity/awesome-github-profiles#76]
![bolaji](https://user-images.githubusercontent.com/64528871/92191405-9e178e80-ee5b-11ea-8e21-108a54d77075.PNG)

**Comment by jomefavourite** [comment]
Voting for him

**Comment by eddiejaoude** [comment]
To vote can you add a 👍 reaction to the issues please (top right of the issue there is a smily face, you can click on the reaction there)

**Comment by jomefavourite** [comment]
Okay, all done

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one.
