### ISSUE TITLE
Issue and Pull Request Templates

### ISSUE THREAD

**Issue by Akshu-on-github** [EddieHubCommunity/awesome-github-profiles#790]
<img src = "https://user-images.githubusercontent.com/61582763/138206949-80b7164c-61e8-4bd5-8075-b5f94824f982.png" alt = "community profile under insights" width = 25% align = "right">

## Description

May I create Issue and PR templates for the repo? Having the same could make things a bit easier while boosting the Community Profile

**Comment by krishguptadev** [comment]
> Ah... I did mention that I'd like to take this up

Oh, Didn't see that, sorry! Feel ree to work on this

**Comment by Panquesito7** [comment]
Feel free to work on it, @Akshu-on-github! 🙂
