### ISSUE TITLE
awesome

### ISSUE THREAD

**Issue by saurabhprasadsah** [EddieHubCommunity/awesome-github-profiles#810]
awesome profile..///

**Comment by CodingSpecies** [comment]
@saurabhprasadsah do you want to add yourself to this repo? If so follow the above steps. If you need any help, feel free to ask.

**Comment by saurabhprasadsah** [comment]
![image](https://user-images.githubusercontent.com/42804047/144072961-8b61f016-51a2-4ea1-b649-82aa812d694c.png)

**Comment by saurabhprasadsah** [comment]
this is my profile.. you have check this one..//

**Comment by saurabhprasadsah** [comment]
@CodingSpecies check pls ones.

**Comment by CodingSpecies** [comment]
Yes this is the screenshot but now you have to add yourself to the data.json file and copy this image url lingo it. If you need help feel free to ask and see the guide which I sent previously above @saurabhprasadsah 
Thank you

**Comment by saurabhprasadsah** [comment]
okay thanks @CodingSpecies

**Comment by saurabhprasadsah** [comment]
okay
