### ISSUE TITLE
Portfolio 

### ISSUE THREAD

**Issue by Mhassanbughio** [EddieHubCommunity/awesome-github-profiles#818]
Profile Linked with Portfolio , When click on profile redirect to portfolio full deploy on github.io

**Comment by CodingSpecies** [comment]
@Mhassanbughio 
### What to do:

- [x] Take a screenshot of your profile, up to where it says `pinned repos`.
- [x] As you just took a screenshot, just `ctrl v` it into the issue. Or, save it to your computer and then upload it to GitHub, and it will generate a custom image URL, when you copy image address.
- [x] Go to your forked copy of the repo, and go to `data.json` and add your name, paste in the image url and fill out the rest.

**Comment by Mhassanbughio** [comment]
![image](https://user-images.githubusercontent.com/60064591/139942432-14476448-b228-4e0e-939a-fb38a75cc993.png)

**Comment by Mhassanbughio** [comment]
![MFoAYqQlSA2UYVBLUtV4pg_thumb_364](https://user-images.githubusercontent.com/60064591/139943235-68ea4d39-9962-46fa-b6f9-584385f77a63.jpg)

**Comment by CodingSpecies** [comment]
@Mhassanbughio please can you reopen this?
