### ISSUE TITLE
Javeria Saeed Abbasi

### ISSUE THREAD

**Issue by Javeria-Saeed-Abbasi** [EddieHubCommunity/awesome-github-profiles#822]
![screencapture-github-Javeria-Saeed-Abbasi-2021-11-02-23_16_17](https://user-images.githubusercontent.com/48078927/139922335-ee8d4fc0-bc58-4e96-bce7-064260e88b45.png)

**Comment by schmelto** [comment]
please follow [this guid](https://github.com/EddieHubCommunity/awesome-github-profiles#how-can-i-add-my-github-profile-%EF%B8%8F%EF%B8%8F) on how to add your profile

**Comment by CodingSpecies** [comment]
@Javeria-Saeed-Abbasi do you need any help to add your profile? If so, please see below on a guide.
Thank you.

-----------------------------------

### What to do:

- [x] Take a screenshot of your profile, up to where it says `pinned repos`.
- [x] As you just took a screenshot, just `ctrl v` it into the issue. Or, save it to your computer and then upload it to GitHub, and it will generate a custom image URL, when you copy image address.
- [x] Go to your forked copy of the repo, and go to `data.json` and add your name, paste in the image url and fill out the rest.
### Now, just open a pull request with your changes!  🎉
