### ISSUE TITLE
Anurag Pathak

### ISSUE THREAD

**Issue by AnuragThePathak** [EddieHubCommunity/awesome-github-profiles#874]
![README](https://user-images.githubusercontent.com/75429250/143869337-38c7d5d6-f496-4435-9970-6d0831931884.png)

**Comment by krishguptadev** [comment]
I would prefer a screenshot like:

![image](https://user-images.githubusercontent.com/91655303/143864342-78e9a868-e7bf-4453-9945-3d51fd911e50.png)

**Comment by krishguptadev** [comment]
> > I would prefer a screenshot like:
> > ![image](https://user-images.githubusercontent.com/91655303/143864342-78e9a868-e7bf-4453-9945-3d51fd911e50.png)
> 
> Ig I can add link to this image itself?

Yes! So are you making PR?
