### ISSUE TITLE
[BUG] Website not being updated

### ISSUE THREAD

**Issue by Panquesito7** [EddieHubCommunity/awesome-github-profiles#877]
The latest deployment was in August, looks like there was something wrong here. 👀 
Maybe we need to make another commit to deploy it. Should we do that?

![image](https://user-images.githubusercontent.com/51391473/144645063-16d72733-ffa6-4adb-abc5-ebce5efb1860.png)

**Comment by nhcarrigan** [comment]
It looks like the GH Pages is set to deploy from the `gh-pages` branch. We'd need to merge `main` into `gh-pages` to trigger a new deployment.

I'll look in to this later today when I have time to confirm that the current state of `main` will deploy correctly.

**Comment by Panquesito7** [comment]
Actually, I think it deployed well (see https://github.com/EddieHubCommunity/awesome-github-profiles/commit/c33d0333e6984686bd5e887dd7e74bebf5033978)

**Comment by nhcarrigan** [comment]
That's a commit on `main`.

The concern is we've completely modified the layout since August, and I need to make sure the new theming renders as expected.

**Comment by Panquesito7** [comment]
Ping?

**Comment by nhcarrigan** [comment]
Deploying via #982 pending Eddie's confirmation.
