### ISSUE TITLE
Dmitry Labuzov

### ISSUE THREAD

**Issue by codlipa** [EddieHubCommunity/awesome-github-profiles#880]
![codlipa](https://user-images.githubusercontent.com/87143407/144700867-49ff3d28-1c45-4a93-966a-cef5266bbec8.png)

**Comment by codlipa** [comment]
Hello there, I had a problem while going through the guide. I can't go to data.json and add my name 'cause it was removed

**Comment by nhcarrigan** [comment]
Hey there! Sorry for the confusion - the instructions in the README are outdated now.

You'll need to create a `codlipa.json` file within the `profiles` folder and add your information there.
