### ISSUE TITLE
[DOCS] - Update Instructions in Readme

### ISSUE THREAD

**Issue by nhcarrigan** [EddieHubCommunity/awesome-github-profiles#883]
With https://github.com/EddieHubCommunity/awesome-github-profiles/pull/782 having been merged, our instructions in the README.md file are now outdated.

The text needs to be updated to explain that instead of editing the `data.json` file, the new profile is added by creating a `{username}.json` file within `profiles`, replacing `{username}` with the author's username.

**Comment by Pradumnasaraf** [comment]
I will we working on this issue :)
