### ISSUE TITLE
Add Link to repo in the about section

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/awesome-github-profiles#887]
![image](https://user-images.githubusercontent.com/30869493/144743669-3ddc4cc6-111d-4b69-b955-154e6aafbb48.png)

**Comment by schmelto** [comment]
@eddiejaoude I think only you can do this.

**Comment by schmelto** [comment]
@eddiejaoude a friendly reminder :)

**Comment by eddiejaoude** [comment]
Thank you @schmelto 👍 

Should be done now...

<img width="971" alt="Screenshot 2021-12-13 at 21 50 10" src="https://user-images.githubusercontent.com/624760/145824301-30587f7c-b867-42ab-aefd-0e1a883cc36e.png">
