### ISSUE TITLE
Peace Cyebukayire

### ISSUE THREAD

**Issue by Cyebukayire** [EddieHubCommunity/awesome-github-profiles#957]
## Profile Screenshot
![image](https://user-images.githubusercontent.com/55869293/158945104-1a53a42b-50dc-4b85-9140-d53a81a97a9c.png)

**Comment by starlightknown** [comment]
hi there, would you like to open a PR with the format given in readme for your profile to get added in the repo?

**Comment by Cyebukayire** [comment]
Hello, I think did that before
let me check it out again

**Comment by Pradumnasaraf** [comment]
Thank you for opening the Issue. I think it's no more required. Feel free to raise another one if required.
