### ISSUE TITLE
Anushka Raj

### ISSUE THREAD

**Issue by Anushka-codergirl** [EddieHubCommunity/awesome-github-profiles#961]
## Profile Screenshot

![screencapture-github-Anushka-codergirl-2022-01-12-12_21_59](https://user-images.githubusercontent.com/43162561/149078859-2fa22886-13fd-44d3-8a3a-6726bc8fc506.png)

**Comment by Cyebukayire** [comment]
I like your GitHub account
keep making the squares Green:)

**Comment by Anushka-codergirl** [comment]
Sure! I will try my best :)
