### ISSUE TITLE
Aditya Arpan Sahoo

### ISSUE THREAD

**Issue by arpanaditya** [EddieHubCommunity/awesome-github-profiles#964]
## Profile Screenshot

![@arpanaditya](https://user-images.githubusercontent.com/75975428/149463291-061db5e2-5228-418b-b70f-21ae7f0b75ad.png)

**Comment by Pradumnasaraf** [comment]
**Hey Arpan, thanks for opening the issue:)**

Please shrink the image (GitHub Profile) to a single page.
