### ISSUE TITLE
Savio Martin

### ISSUE THREAD

**Issue by saviomartin** [EddieHubCommunity/awesome-github-profiles#98]
![Savio Martin](https://raw.githubusercontent.com/saviomartin/saviomartin/master/assets/saviomartin.png)

**Comment by w3bdesign** [comment]
@saviomartin @AllanRegush 

The screenshot listed seems to be broken.

I'll open a new PR to fix it.

**Comment by w3bdesign** [comment]
![image](https://user-images.githubusercontent.com/45217974/104979077-b3a0e580-5a03-11eb-892f-8eaa3b8bb214.png)

**Comment by w3bdesign** [comment]
Fixed broken screenshot in https://github.com/EddieJaoudeCommunity/awesome-github-profiles/pull/259

**Comment by saviomartin** [comment]
Oh, thanks for letting me know

**Comment by w3bdesign** [comment]
Fixed in https://github.com/EddieJaoudeCommunity/awesome-github-profiles/pull/263

**Comment by schmelto** [comment]
Due we close new issues on PR merge and voting is still possible on closed issues I will close this one.
