### ISSUE TITLE
Shivendu Kumar

### ISSUE THREAD

**Issue by IAMSKJha** [EddieHubCommunity/awesome-github-profiles#980]
## Profile Screenshot

![](https://user-images.githubusercontent.com/51878265/150308194-ef2dfa21-6ce2-4db9-a86b-72c83b6d1fd6.png)

**Comment by Pradumnasaraf** [comment]
Hey! you can use this screenshot instead, your whole profile is visible and the window taskbar is also not visible :)
**Thank you for opening the issue**
![shivendu](https://user-images.githubusercontent.com/51878265/150308194-ef2dfa21-6ce2-4db9-a86b-72c83b6d1fd6.png)

**Comment by IAMSKJha** [comment]
> Hey! you can use this screenshot instead, your whole profile is visible and the window taskbar is also not visible :) **Thank you for opening the issue** ![shivendu](https://user-images.githubusercontent.com/51878265/150308194-ef2dfa21-6ce2-4db9-a86b-72c83b6d1fd6.png)

Thanks, I am on it .
